// SPDX-License-Identifier: GPL-3.0-or-later
// This file is part of Robot Components
// Project: https://github.com/RobotComponents/RobotComponents
//
// Copyright (c) 2020-2024 Arjen Deetman
//
// Authors:
//   - Arjen Deetman (2021-2024)
//
// For license details, see the LICENSE file in the project root.

// System Libs
using System.Collections.Generic;
// Grasshopper Libs
using Grasshopper.Kernel;

namespace RobotComponents.ABB.Gh.Utils
{
    /// <summary>
    /// Represents the interface for components that are managed by the document object manager.
    /// </summary>
    internal interface IObjectManager
    {
        #region methods
        /// <summary>
        /// Detect if the components gets removed from the canvas and deletes the 
        /// objects created with this components from the object manager. 
        /// </summary>
        /// <param name="sender"> The object that raises the event. </param>
        /// <param name="e"> The event data. </param>
        void DocumentObjectsDeleted(object sender, GH_DocObjectEventArgs e);
        #endregion

        #region properties
        /// <summary>
        /// Gets the last set variable name.
        /// </summary>
        string LastName { get; set; }

        /// <summary>
        /// Gets a value indicating whether or not the variable names that are generated by this component are unique.
        /// </summary>
        bool IsUnique { get; set; }

        /// <summary>
        /// Gets or sets the current registered names. 
        /// </summary>
        List<string> Registered { get; set; }

        /// <summary>
        /// Gets the variables names that need to be registered by the object manager.
        /// </summary>
        List<string> ToRegister { get; }
        #endregion 
    }
}
