//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotComponents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Auto_Icon {
            get {
                object obj = ResourceManager.GetObject("Auto_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Auto_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Auto_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChangeTool_Icon {
            get {
                object obj = ResourceManager.GetObject("ChangeTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChangeTool_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("ChangeTool_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CodeLine_Icon {
            get {
                object obj = ResourceManager.GetObject("CodeLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CodeLine_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("CodeLine_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_Icon {
            get {
                object obj = ResourceManager.GetObject("Comment_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Comment_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructExternalLinearAxis_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructExternalLinearAxis_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructMovement_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructMovement_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructRobotInfoComponent_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructRobotInfoComponent_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructRobotTool_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructRobotTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructSpeedData_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructSpeedData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructTarget_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructTarget_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("DigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DigitalOutput_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("DigitalOutput_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExternalLinearAxis_Icon {
            get {
                object obj = ResourceManager.GetObject("ExternalLinearAxis_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExternalLinearAxis_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("ExternalLinearAxis_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlane_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlane_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlaneX_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlaneX_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlaneY_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlaneY_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ForwardKinematics_Icon {
            get {
                object obj = ResourceManager.GetObject("ForwardKinematics_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetAxisValues_Icon {
            get {
                object obj = ResourceManager.GetObject("GetAxisValues_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetController_Icon {
            get {
                object obj = ResourceManager.GetObject("GetController_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("GetDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetDigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("GetDigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Info_Icon {
            get {
                object obj = ResourceManager.GetObject("Info_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InverseKinematics_Icon {
            get {
                object obj = ResourceManager.GetObject("InverseKinematics_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1nmBRFtIZnunt6pqdneshBSZIkSc4ZySA555xzVJKI5CCgKCA5ZwREguSMAiIoklFQlKASTQjCfc/p/XGf+/PyPh/fV6erq6qre2d32VkNBAOBwAv+iMufmMFfzRp279G3X+V+ffr065svS9MuAwf16Ne3XPH8hYrlL1SqUPGi+QsXKlioUL4slYf0HjxkYJdyfbsMGTywQ+98WeoP6di7R6faXYY17terS99yxYoVLlyyUJdSJTqVKFasWJGCIZklpQ6ev3qXfn26DB44LH+dLoO6W9TDQ/15oh0GdureY2iXIp37OP36d+nbd8jAjoOszh0Gd5BOkUjEkCUmezUQKIuP71d2mmMSEvJXyzlGwPh3tBGoO8fQy3n6wgikSrq0m+cu1K1+59vk+38OJBsbzPrgtc9fbv2M42mS+pYMvxQIHETfZCyyaO8/P7/4/3rg//wJHihzuEOOe4fcs9Za/HVnw6PXg4GelQOBdyr8L+3/X/o/taQ//jqDuBEw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_base_link {
            get {
                return ResourceManager.GetString("irb1200_5_90_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_5_90_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_5_90_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1l2NRWtIVnMpPJTJKhSEtxd3d3K9oChUILxV2LFnd3CqVoKVLcrTiF4hT3FneXYkUK99078+M+9+flfRZrnZ3k5OTkJJ8AHz6/z+f7wC9x+eUa/FanZqvWHTqW7di+fccO2VJ91bxzl9YdOxQvkCN3/hy5C+cukC9Hnty5cufOlqpst3Zdu3VuXrxD825dOzduly1V9W5N2rVuWqV5z1od2zbvUDx//jx5CuVuXrhg04L58+fPm8uUsyTQznN81rxj++ZdO/fMUa15l1ZB6lZ37zx2485NW7Xu3jxvs/aRjt8179ChW+cmXYLNGndtLDuFw2FDhhg3o89XDB/asdiYSIDwkfxW5pHhM970N3wFHhl6OW8/GL6PY5d249TZzz+7ezLejpu+uIP9aZ5k35S0/ju2v3/o7VvITuLz9Uvm851Invfnbf/e/PD/dd//+VVv/qtd88obf8zLVbys32eVJZddXOBJWZ9vQMn/pR3/S/+nFvvljdOPG74ACoKJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_1 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBXlF7dn9uTeQ5eUIAoCgjRIN9Ld3d0N0iBSKt0KAiKiCKLSpaSKYICKgQoSf0CQEEHyvdd69of3ej++577W+f3WmplnOp599t7Hsi3LesyPqPykiPGrZZNevQcMrDawf/+BAwo+1aL7kKG9Bw6oUKpQ0ZKFipYpWqpEoWJFixQtWvCpasP7DRs+pHuFAd2HDxvSuV/BpxoN79Kvd9e63Uc3G9i3+4AKJUsWK1a6aPcyL3R9oWTJksWLeDKX9Np4oZrdB/bvPmzI6EL1uw/t5VIPRpj5JDoP6dqr94juxbv1jw8c1H3AgOFDugx1u3Ue1llGCsMwJouYJq9llUenDiz/atzBpJZfbbK7VuzehJjVILurq3P/cczKkFy1cyd/bFDz0om0+85baabYT19/fke2dg8Ynik5buntuSzr3XyW9d2TxVfsuXv+8f+vWv/Pj22t3v+ydWX/V1+9Vc22lle1rStVn7rdvbplTaz0f8W+/yv+n1ryJ5ZsLgYO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_2 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1l2BVVuIb37JqZvWfvj+7u7u7u7u5O6ZRQEWlQRBEkRLpEuhtpEBCkBWkBAQGRPPf7zv5xrvPzfPf18DzrnTVrrYkdX+IxPB7PBz7E5cPx8k/TBt269+lbsW/v3n375ErXpHP/Ad379ildJE/+wnnyF89fpFCeAvnz5c+fK13FQb0GDurfuXSfzoMG9m/fK1e6eoM69OresWbnYY369uzcp3ThwgUKFMvfuXjRjkULFy5cMF9AZkmog+ep2rlv784D+w/LU7vzgG5+6uZgd55Q+/4du3Uf3Llgp95234869+kzqH+HAf5O7Qe2l06WZXllifGyejyl8HF9S022fYQ4+efYGK/H+3q017N7jFcP580HrydR7NBunbtQp+r9s/F33/bE+9TI8CT31pSt3rJ9fKxvsRRJPJ4cST2eM6kLztv56vaH/697/s/HgzsL9xmexft6jS9fySg3vaLhWVfhk9v9K3k8Y8r+L+3+X/o/tdiHu04Dl+QjSfZ7AuAl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_3 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ112BXVG66nY0t3d3d3pzQSioS0SreAICkhKSjSJYIgIC2gNMJPARUpCekGEeQDRBQ49/vO/uNc58/DfT08z3r37DUza9bMnu9j741hGobxkj/i8ieRxV9vNHu3W+8+Nfv06tWnd6Fsr3ftP6Bbn96VyxQpXrpI8fLFy5QqUqJ4seLFC2WrOajnwEH9u1bu3XXQwP4dexbK1nRQp57dOjfoOrRFnx5de1cuXbpEiXLFu5Yv27ls6dKlSxZzZS0ptfMidbv26dV1YP+hRRp1HfCuQ91/L1pPrGP/zu92e69ryS69wj59u/buPah/pwFOl44DO8pCQRBYsonJ8hpGJXxcn0pTQpuQVP769FvfsJ6NtIyJBPnz70vLSBXftWsnfmtc9/bx5LuvG8nGmjkeFN6ese1/PN40vmy5RuUNY8FrhnEsc8lFO59ef/n/68b/8+fl7nE1T1zosS/TpCa16lV/VtM0etYwqw2oZRijqv5f2v1/6f+pxf9Y+reJS7JJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_4 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ133I9l2MbvPX7DSmb23iN7z5REisree2ZvSiIpZJYkQlMlCtl7hGSPpISyE7J5v+d5P3+8n/fP1/dzOI7rvK77uq/7un/jeR6/pwzTMIxH/BGXPwmLv15+oWu33n1q9+nVq0/vojlf6tSvf7c+vauWK16qbPFSFUuVK1O8dKmSpUoVzVl7YM8BA/t1qtq708AB/dr1LJrz+YHte3br8GynoU369OjUu2rZsqVLVyjVqWL5DuXLli37ZElXzvKYTl68Xqc+vToN6De0+HOd+nd1qPuDovPE2vXr0LXboE5PduwV9unbqXfvgf3a93c6thvQTgYFQWDJEtMUMIwq+Lg+VSaFNiG1/FX/imlYd0dbRrUr0QXde2QZ6VMu7czBIw3rnT+Qdv1ZI81YM/c/xVZlbXmffi9lbIXfMhhG2ccNY3+2Jz9ae/vso/+vG//nz5gZW2tvuWlu+j32Qh3TcOp06Vy81uXXutehp/r/0vr/pf9TS/lj6d9cItjaFne0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_5 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp5NJVt+O+f/agUFRlSKTKUBpFkyrArlUaSJJmSkAzbkHkqEr1IJUMZizIThcwp85jKmBAbITZ2bON2rnt7f7/1O791zlpnnbXOX8f1eb/7+u77ue/rvp5n33u1e1cYAcOwJQiUUazH4UXr0i0zK5IyydKSZCW684qxrZ0ZyUpRWkxCSkxCTkL6sNghiYMSEqI7le0t7tjbGitaGdvfsTW0EN150f6GhZnROWPnyyRzYytFKalDh2QljOVkjGSkpKQkD65Gu3AyioupGJMsje/YOotdMLa7tQrGmR2W92ExtDW6ZeZgLHnTch3J2tjKyt72ht2qm4Z3DNGktWvX4qhFdhEMU4DsQ1IIWMcEhg29RIljGD7niWNPxJdvZ34Jx7j+vTXy91ZVlaFvm0r6MXZvguD4gTxe3QW4rv3vXNkmKHwZ9HWHZHTRTP/S/23G/lssLTGdIGCxpdYXtE8Qjq5G/pjWKaMTGHaX+F9U8l/0P439x2eD4YxXAmTkmMAh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_6 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_7_70_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_7_70_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBRHtLVnerqnp0dwd3eHg7sFDe4QggaH4BYCwSG4BbfgEBwCBBICBA3uTiC4O8G+d++eH/e7Py/vs7JW7a6qrq7uMxyZQzxej8fzmT/i8ids8J86tdu179K1XNfOnbt2yZGmfpvuPdp37VIiJlfeXPnz8CdX3kI50pTr1alnr+5tSnRp06tn9xadcqSp2atlp/atqrbpV7drxzb0jsmXr3DeNkUKtSoUExOTP48lZ4ivE+f6ok3Xzm16du+Xq3qbHu1M6nZv9xzBFt1btWvfu03+1p2drt3adOnSq3vLHmbrFj1bSKdAIGDI8uJk9nhklLPfCjs+Qmz5j3nZ6zH++97wfLjk9bz/bHgSULx1+tyXX9w7Fff3fz1xhnrTPc25LXnTDxw7Tp+YpAk9nt3JPJ6TKfPP2/n238//V/f8rz/eP4rtSZ/x8Z8fj5sr8LIFVz8v6/F0KOfxDC71P/T7/9D/V5P7oRMZ7nS44fFxya5bJBP3kwS/x1b8ngA4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_base_link {
            get {
                return ResourceManager.GetString("irb1200_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ112BVV2O5n7z17z549Q4d0h0g3Snd3SHdKSokSAiJdSkqIiiIgIqBIiSBKh6SAgHR3N3y/51n7XNd3zp+H33V73+uZmTVr1qyZN4T3tQKWZb3mj7j88YP8p2GDrt169a7Yu2fP3r3yZGrSqW+/br17lS6ar2C+wgX4k69g8TyZKg7o0X9A306le3Ua0L9vux55MtUb0L5Htw41O33YqHf3TuxdtFChEgU7vV28Q/GiRYsWLhCWMyTTjvNV7dS7Z6f+fT/MV7tTv642dWegOUesXd8OXbsN7FS4Y0+3d59OvXoN6Nu+n92xXf92slM0Gg3K8BLntCw5yt0e9t0QIZH8p0i2oBV89nHQykN4/jpoJad44fDROlWvHkqy6aKV+JNAljt516Vt+YJtFvsUfZnCsoals6yD6Qt/ufHJxdf/v279P396f/t4y4rKwT+/LVC6IsOuSK64uNgd8vCy/0ub/pf+r5rcD+0oqP8N4EErhGwIowiEqUjbsaKWC44V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_1 {
            get {
                return ResourceManager.GetString("irb1200_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nL1nuNRUG7adZCbJTGboHUGqIAoIKIIoKiKgICAgvXdQAemiFOm9995770W6NJFeVUC6gMAjIh2E77zvNT/e73j/vZzHta9r3UlWVjIlZfYeLNuyrBf8E5d/cYcfVSq3aNm6Tck2rVq1aZ03a7Wm7dq3bNO6eOH8BfO/WYB/+QsWyZu1ZMevO3Rs17R466YdO7Rr+HXerJ93bPR1y8blmnb5os1XTZm7cKFCRQs2fadI4yKFCxd+s4Ara0ilHecv07RNq6Yd2nXJX75p+xZh6n4ns46gYbvGLVp2avpmk1bRNt80bd26Y7tG7cNNGnZoKDNFIhFHhpc8t2XJUtG9bjwaIiSTH3NeCVnOkx6ONYXw9IVjpaZ45cTpCmVuHE+x7aqVvLed/U6+jS/Veca0b5in8IKXLeu7PJZ1LPOb07Y8uvri/9Wt/+vfrJ2NrZs7Dx6YUdKyJn9kWTc/ytSx/MeW9cMH/4e2/R/6/9Xk8dBuHP1p444VYpNtJWy5Stjy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_2 {
            get {
                return ResourceManager.GetString("irb1200_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nL13lBTVF7Zbnaq6qrvJIDmJEhQQEQEDiqj8AJEsICI556TknJGcJecsOeecc46SJUnOIHzP3qfvWt+9f9551sv7nl2nTp06VT0z3dMzWD7Lst7yIS4fUT//lCtbv0HTZkWaNWnSrOmHGX+q07JVg2ZNv8yXK0+uvB/xkStP/g8zFmnTuHWblnW+bFqnTeuWNRp/mLF0m5qNG9QqUadd+WaN6tA738cfF8hTp2D+Wvnz5cuX96OQHCGpDpyraJ1mTeq0btkuV8k6reoHqTu/mWN4NVrWqt/gtzp5azdxmzWv07Rpm5Y1WwVr12hdQzqFw2G/TC9RVsuSvdydoagbICSUf4LbfZb/ZRe/9Xqbz3r11m8lo3j12Mkfi948mnjjNStRD1/m+zlXp/nlNdsO0SffoySWlfwdyzqSLu/E9c+vvf3/69b/52NClc1bLGvGlrmJsn9rdf2iiGUt/SZvkarfWlbXr/4vbfy/9P+qyfXQgfz6L6el+KwABEnGQ1p1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_3 {
            get {
                return ResourceManager.GetString("irb1200_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ113BRl2LZnd6fnoVO6S7q7uzuVBkEJKRERFUEQKRERkEakpENEUhpRBJEU6RaQEmm+47pm/3i/98+X43dynvc1M/fUPbOzD/ssRsQwjJf8EZc/CVH+ata0R88+fav17d27b5/8WVp26z+gZ98+FUoULFKwWGH+FCxSKn+WaoN6DRzUv1uFPt0GDezfqVf+LI0Hde7Vs0u9bkOa932rG3OXKFq0dJFuZUp1KVWiRIlihS1ZQwrtuGCtbn17dxvYf0jBBt0G9DCpO++E6/A79e/So+c73Yp17e31fbtbnz6D+nceYHbtNLCTzOS6blQ2L2luw5ClvL1WghcjJJG/frpiGdEnH0aNjYSnL6NGSoqX/jjesNb1I8m2XTaSjohku1NgY/rXnjFtPPOUOFzMMDI3NYzfMxabveXR5Zf/Vzf+95+Pclc7duatHcn8UtWbVNlXzTB6Vb25rW11JlT6H9r2P/T/1eR8aD9R/TuCCxEjBiYpdEurjuEanuIaPgSk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_4 {
            get {
                return ResourceManager.GetString("irb1200_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBRXsHbHe1rm4C7BIUBwC4GgQYK7Owd3twDB3S1okBCCQwjuLsHd3V1DCPKtqj4/7nd/Xtbz5q1du3b17t0zg51DPF6Px/OFH+Lyw/Hxn2pVW7Xu0LFEx/btO3bImqpmdJeurTt2KJw3W85suXPwI1vO/FlTlejerlv3LtGFO0R379alSbusqSp3b9qudbNy0b2rd2wbTXXeXLkK5Iz+Nn+z/Hnz5s2dIyhXiKeNs5WO7tg+uluX3tkqRHdtFSBv9HCvYTXp0qxV6x7RuZu3Nzt2iu7QoXuXpl0DzZt0ayJF4XDYJ9uLndHjkVXmgaBj+gliyX8etvd6fB8G+Dw3Cf774vPEJ3nnzPmKpR+ejrPjrif2YG+aF99sSlb/I3N/UZN3QRyPJ2sCj+dUitxzt72/++X/6p7/9WPA1Mkl9rz17r456tuSHs+5Ei1aZCv+xFuVeGCR/6Ed/0P/X06ehzby6X+5LfCjAPg9wZhxiEgIeQwl5AmDiSywkQMR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_5 {
            get {
                return ResourceManager.GetString("irb1200_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp5VM7r++8/z5N2kgrZSoMMDYaUSrMKsZuIlCERpXnUoJEITdIgtgaaZGoXqQylydCgGZGQ5hnRrEm/9/3p+zvne9bvnLV+66x1/jrdr/3uej/Xfd/XfX2e535kr4ViUBQ1jUEiGfOZ+GGwx9rG0UnDycHByVFi+T4LF1cbJ0dVOUlpSdkNGJLSChLLNU7Yu51wsVB1tDjh5mJqL7F89wkze5tjuhZehk52FlgtJyOjKG2hpHBMQU5OTnYDKzmBhy4sqWnh5GDh5uIludPC1XoO8mzuM2fMM3U5Zm3jbiFr7sDudNzC0fGEi5nrHHNTN1OyaO7cuUzS3gJxiiK72EtZ57OzwHCTH7EiFMUcP82kImEmppnUYiTb333Q0+ypXVjYQS04x1j5c32OwKFJzFlijZw2ihlCb4Vk4/N/dUz/30bqv4w6DYpKfG5TtXkbdaae+C3GJTrbKOqM+r+p8N/0v+TI50GXYdI/GYhMigWPzKCZQ7HSzKH+AGzQXMAO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_6 {
            get {
                return ResourceManager.GetString("irb1200_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3XI9f/DD+s69RyJ7JSEYqlZaWyoqiiEgJLZSWrZQ9kxEqImWFrDIS5UOLJFS2rKRBpUJR6nfevvf9eNy/+8/7/XzUdfV2va/rnHOd65zX67wBCABo5y/FVvFSRvzXrOmLFvsH2AQsXRrgP3LALK/gZYsD/M0NtfW0dY1HGRpo6+qO0tcdOcBmhd/yFcFe5v5eK5YHL/AbOcBhxUK/xR5TvNY4Bfh6+ZsbGOjpGet6mRh5GBkYGOiPooqLdP13bu2JXgFLvZYHr9G291q2iPD3hZX/cxl5QbDHosUrvfQ9l0oBgV7+/iuCFy4jnguWL1AcJIoiUpRQZSgAZnxrvkiMkDDf6aT41bgLAPQnHIGKXf9Tm5Z2BLr9r5p9LnkxdWJVcec75UBlExz0XetmX9dW/u+X/texxn2UALCmABSp6h/LaC5v/3/dgv/rZTjwTlbh+qCsCT9n3YJgl015VpDNn/YRNgCst/w/fu78Hz//v/f+960B6N9vEShz3UAf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1660ID_base_link {
            get {
                return ResourceManager.GetString("irb1660ID_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1660ID_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1660ID_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxjmB1ZuCjgslbZuzZjd9KxOrY1sTq27Yk58cS2baNjJxPbtnm/6nN+3Of+vPU+tas6s6t2aa31LdRgOIZhf2Dyl/4kEvBRs1qr1h06Fu/Yvn3HDpljNZt36dq6Y4eE3HHZ4+LzZsudKy4+PluO+Myx4t3bdevepXlCh+bdu3VJbJc5VqV7k3atm5Zv3rtGx7bNOyTkypU9e9745vnyNM2TK1euHNlo/0eM5H3HlW7esX3zbl16x1Vs3rUVBf/O9vifnxESuzRt1bpH8xzN2vMdOzXv0KF7lyZdqWaJ3RL9L3EcR/hHqKbDsIKwTGjFjeVJWFH8j0efcYz4PpDArn3+n/P58YfAzP89s4eXrlQq/eyitu8Rpg7BU77NsiNY/yf89wX/+928aloM83QMuxDOMXfP10d//n+X2P8z/TGGHmKxVId+/PlarNPwOcWxQUWKr3uYugSGDSr8f837/q/5//m3/52I5E8SYwCPiZgCdMzFwiCGpcbSgyxYLiwf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_1 {
            get {
                return ResourceManager.GetString("irb1666ID_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNppOFVf2DDwPa89HSqhUmnUYMpQyFgqJCRRMhUpZIiQIaS5FCJJikRzKhUSKkqIQhnKTGhApkyh3uX/PB/e6/34rt91husc9rD22ve6770PgiII8g+2ydfJxmPwyWKLk7O7h66Hm5uHu8w8C0evA84e7pqr5BTlFFRXrFopp6CwQklBZp6uj6u3j5ejprujj7fXLleZeZt97F2dHQwd/bd67HN011y5UlFRVcFRTcVBZeXKlUoryMmViPy3bDk9Rw83R28vfzkjxwNOBPwc+P7PathdXg5Ozr6OSrvdGI/9ju7uPl72B4jdu7x3Tf4RTdPY5BZOWYIgGvBV04k+y+DwjfDk0/VLCIL9CcGQi5f+Z2/G/mHI9P/ds7bKGmO9H5+mvmxHphxFF/TKZklYj8Pvbf/3b1X3ChCkD27KxzlKCbkj7f/+f1+R/6d5DwWuFT186PXM6YW6uzE33WlIVX6k4Oo6BDms/X89Xv5fj//ns/9tkztOIijCQpPvKQhH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_2 {
            get {
                return ResourceManager.GetString("irb1666ID_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxlWFtZ1DDsuLsQd3cjngAJkBASCCTUddoydXf3Tn2m7u3U3XXq7m5Td/d26vounu/58V7vz2/dVxKuOId99l7rnL1BIBEIxC+ImtuaoKDgqnamVesOHQs7tm/fsYNZXru6S9fWHTuEPVan1eGze9xWh8Pucpjlhd3bdevepTrcobp7ty6/tTPLK7o3a9e6ebK6d1XHttUdwm630+lzVPu9zb1ut9tlx9Z8CPt/3tsar+7Yvrpbl97WsuqurTBwP77H//cxpN+6NG/Vuke1q0V7YsdO1R06dO/SrCumxW/dfqt5EoFAQNV8Q4YOgQjBbbgVYSwRDT/Qa642UHEI1NeBKMQS+KEmvv1CITj/+5s9uPhvefzpBeaehwjGUKTyjeUfUcPv8HiH/32uj9UNgTgA73te4pq76/PDX/9/bxH/T9S+hNyvwLzYf6Zh/6IPwycWdkPIC2f/XF2EQAzK/78ue/6vy/9z3/8G6n+usQgKYCP4CCnQIEwIJ/Ah8hEx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_3 {
            get {
                return ResourceManager.GetString("irb1666ID_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxllBtHtCBgMTPziJkZRwwzI9kxMzMzO2bHEHPMzEwxM8TMjDHFzMwe23vH+368sz+3vtNqnZHULeiuureqehBIBALxE0rFuqJQUHBTs2rrNh07JTt16NCpo1les0XXbm06dYx4rU6rw2/3eqwOh93lMMuTPdp379G1RaRjix7duzZpb5b/1qNp+zbNylr0qd6pXYuOEY/H6fQ7WgR8zXwej8dlx1bshP1r29Zsi04dWnTv2sdaaNGtNQb+ju/5f3dDatK1Wes2PVu4mncgdurcomPHHl2bdsM0b9K9ScWTCAQCquIdMnQIRBjWkdaEMUQ03KFX3Iy/jkWgvg5EIYbCnYry7ScKwfmfT3b/4pVK2ScXmHsfIBhDkcrXlu3i+uXweNn/PNc/sDMCcVOPQJyXuubu/vzg5//vGvH/lBvlY5Prbi/651L/aSnjgMapdz/1SfE/K1MIxKDo/1r2/q/l//nb/xTUr1ssggRoCBaCB0QIOUIHrAgvIgqyiAKi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_4 {
            get {
                return ResourceManager.GetString("irb1666ID_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxlmNNY3CjwJm2kaZrU3d3dBxjcHRa3AQZb3AZ3d3fZhV3c2cXddXFffHB3Blnuv9z3w/vcj/f8nmn6zEyTJjk953+sHITD4fyAlN1mE43CQ73a7dp37lKmS6dOXTr7TPXyu/do36Vz8UQgEginQol4IBwORcM+U5leHXv26p5fvHN+r57d8zr6TDV7tezYvlWV/L51u/ya37l4PB6JpML56WSrZDwej4aw7EGkP/cdqJDfpVN+z+59A9Xye7Tjwe+J3v/3MFRe91bt2vfOj7buxO/SNb9z517dW/bgtc7rmZf9J5Ik0ew7FDk5nGKwLd6OnMDnwhM2+3CvH5eDfhmMci734/48m68/UI7sf86s8OKV6hWeXBDvfcARDUcsr/3btU2+wd8X/c//psqV53CCGg7nvD66aPfnBz/+f7ec/ycpz5Qq269UswNXhPPLYqbOZfEHi0oL364sy+EMyf1fP3v/18//87v/SejPRx6HBEKOmKMCeo6Z4wIBTgwu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_5 {
            get {
                return ResourceManager.GetString("irb1666ID_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNl1VBVf+Cj86RBbAUFKQVBpkC4DQaRUVJAOAWnpDgNBEVBUkFZBLEJEVKRUUkJEpKSRlpBueLff371r3ff+eeezzpmzDufsOTN772c/zwDBEAStg+3f/t+2EQFP589csnF0Oubk4ODkKMB13tLF1cbJUUFSSExIVFpEUkJIVFREXFSA65i7vZu7i6WCo6W7m4uZvQDXKXdzexsLdUvvs052lo4KEhJiYtKiljJSFlISEhLiIvi/g+z4r20hVUsnB0s3F28hTUvXSxh4n/T4n8NsMHOxuGTjYSl+0YF2umzp6OjuYu6KXTRzM/v3IYqikH+/cCsfBMmDvcIl6jaNghdb/j01OEEQshSIQBVO/3M2y+sItPN/nVnfz2Yt1eGGbcX90NZr8N6/gnm7DVfA3yP/12elw2kIigPN/GAXTypc6F//f91D/9e2Hmin7A6d+LJeF69s+emy8rlq1aPSp54rQ1CQ0v/xKP4/Hv+/9/5310DIf884tAHYCjFBbAA7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_6 {
            get {
                return ResourceManager.GetString("irb1666ID_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jlCXrsrVzIRczF9u2bdu2bdu2bdu2bdvmbtv+njeqftzvjnHrOZFzxox4M7Oqz+jdu7U1i6Zp//hQqj4MK5dqlVq0bNe+cPu2bdu3S5OgWtNOnVu2b5c3W7qMOflfppxZ02XMkCFjmgSFu7bp0rVT07ztmnbt0qlhmzQJKnRt1KZl49JNe1Zp37ppu7xZs2bKlCNj05zZG2fPmjVr5gy6ekhY7p2ueNP2bZt26dQzXdmmnVvYyZ3dIh7jadipcYuW3ZpmbtLW3b5D03btunZq1NnepGGXhmrJ5XJZ1RsGkmtaHnRixzJj3DaMX13yTLZp1p/9rVqGyTb5bH79s2pRIj+zJ1eulyv+4nJw/1MtMNiS6H3anbHr/Gb+fVLEbo6U0TVteFjTLsXNPG/v96f//i9d37pFiduFNx8YfmhEgrhvDxSot6ukYW0w8MChNp/2vvnxpID2vz7yTz1xuNqiAYdTtT20u2PCkYXxhRfaqhbWtAH5/0ft/x/1/2Xq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_0 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1juCTJt+/xzCwjUZXVtm3btjFt27Zt27Zt2562bfN+I3penHue5/Tnrly/WBGZu2rv/+menu7ZV1EVRfnDD9HFj6DGpWrFZs3btC3UtnXrtm1Sx6/auEPH5m3b5MmaNkMO/l/GHFnSZkifPkPq+IU6t+rUuUPjPG0ad+7UoX6r1PHLd27QqnnDUo27V27bsnGbPFmyZMyYPUPjHNkaZsuSJUum9C7xQWz57LTFGrdt3bhTh+5pyzTu2MzJ3NPl74fx1+/QsFnzLo0zNWrta9uucZs2nTs06OhsVL9TfXHI6/Vq4hVayRQlN318+9KjfA6CKS5nrzoU7XtfTTl41SHfzY8/mhL57509vHS1bLFnF0N7HynWQDXh2zTbY9X6yf7I/85mjx9DUYbZinIhTqY5u78++vN/9TTBQsUql1uxb937SPzorrf5s0eN/6LF8Lj7c99a835wzKgFlP/1Q1UGHRw7ufbBN+liFFL3bSj0+8DcQvP7pS+sKP3y/Y/a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_1 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1juCTJt+/xzCwzK6ttTdu2bdu2bdu2bdu2bdt29/3G2v3i3PM8pz83av3Wisio2nv6DP7T01fTNU37yw9V1Q+/wUuVCs2at2lbsG3r1m3bpIpfpXGHjs3btsmdJU367Py/DNkzp0mfLl36VPELdm7VqXOHxrnbNO7cqUP9Vqnil+vcoFXzhiUbd6/UtmXjNrkzZ86QIVv6xtmzNsyaOXPmjOkc6k0iyd1pijZu27pxpw7d05Ru3LGZnbmrS8TbeOt3aNiseZfGGRu19rRt17hNm84dGnS0N6rfqb465Ha7DfUJQ0k1LRd1fPtSozw2gqle8i2xacaPvoaWaYlNvpqffw0t8r+v7NGlq2WKPr9o7X2shQbqCd+l3h6r1i/2fy2OOJvtcTRNGxZJ0y7EyThn97fHf/+v2j/ntgulz87fl/nJl/5pBu3NN25j1ZRTY4zfpy6ZNCRufu1//dh62FegVvVZB1fsWl+wzNDZBRd9qX0gS5uLhTStX97/sfb+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_2 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1ztCPbvvbxSlUFlUoqlWS1bdu2bdu2bdu2bdvmbtu2td7vnN1/3PeOcftzZ55n/mpWJavPOPt078ZVHIqiRPJNpPjmU3mpWrF5i7btCrVr06Zd29Txqzbp2KlFu7Z5sqbNkIP/y5gjS9oM6dNnSB2/UJfWnbt0bJKnbZMunTs2aJ06fvkuDVu3aFSqSY/K7Vo1aZsnS5aMGbNnaJIjW6NsWbJkyZTeKd4kLJ+dtliTdm2adO7YI22ZJp2a68zdXf++jbdBx0bNW3RtkqlxG6Nd+yZt23bp2LCT3rhB5wbikMfjUcUntJMpSm5yQofSow2NEhAvo0xdUX/0U5V+pi6/mp+RqhLx7yt7dPlq2WLPLwX3PVbsQY6E79LsiFX7F9eL/TubvXEMRRkWVpSLcTLN3fPtceT/lVsfTk3Wd9i6/d7JJdunG3Utf+30RvTob7vu7zXl1sHEHb/kV/7Xt8p39+2fmjnKoUmPNxf++FQrnGFij0KRed8VVpT++f7H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_3 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1jtCPbt/fxpFKppCpVSSXZbdu2fdq2bdu2bdu2bdu2bT3ftXa/uM8d4/bnzszfmmsV9v6P0adPn9PnOpwOh+MvP0QXP0yFjyoVmjVv07ZQ29at27ZJHb9K4w4dm7dtkydr2gw5+L+MObKkzZA+fYbU8Qt1btWpc4fGedo07typQ/1WqeOX69ygVfOGJRt3r9S2ZeM2ebJkyZgxe4bGObI1zJYlS5ZM6d3iIWF577RFG7dt3bhTh+5pSzfu2Exl7ukS+RijfoeGzZp3aZypUWu9bbvGbdp07tCgo9qofqf64pDX61XEG9rJHI7c9PHtS43SXYSA+CjtVh3Kj76Ko4BblV/Nz7+KI+LfV/bo0tUyRZ9fDO597LAHOhO+S7M9Vq1f7Ov/zmavE93hGBZ2OC7EyTRn97fHf/+vLk/fa7yvbv+Ln8ql7p//VBPnnhnj+u/Ltybe8/V/luV3/K8fn/P9LlQv6toDf++eL+zIsL3w5USrChas+7Sww9Ev3/+o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_4 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jmB1bt7arlletWqsqtm3btm076bhj27Zt2+aObds2vnvMzo/znes6fb+znmdgjllV3dfO29lJb03XNO0vH6LyYTq4VK/cslVY+yLt27VrH5Y2YfVmnTq3ah+WL3v6TLn4X+Zc2dJnypgxU9qERbq27dK1U7N8Yc26dunUqG3ahBW7Nm7bqkmZZj2qtm/TLCxftmyZM+fM1CxXjiY5smXLliWjWw6JomanL9GsfbtmXTr1SF+uWeeWLvLe8IhjjEadmrRsFd4sS9N2/vYdmoWFde3UuLOraaMujaTJ5/M55A7tFJqWF53QsexovxNjycU469AcP/o5tD9nHOppfv51aFH/PdmjS1fLl3h+MdK+x5o9SE/8Lt2OOHV/UT/6rzfn5EiaNjyKpl2Il2Xunm+P//5fmjpWn+b6nUL74uU96Tp8Lrzgu8Lxex7yVdqX8WymmTEu1C2o/a+PZkOXF9W1xQeahV8uOuv61qJ1tcWFZp14WFTT+hf4H2vf/1j/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_5 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJx3XI/f//+vfV0vGghFi0iINJAU2dl7S9FAQ6mUiLJD0jt7y05G9sjInpGSNBBN2hGljN/jnPrj+/vebl/3z/N6zvM853q9ruj1eZ/XYViGYf7hD9HkjxqHy9SJCzx8fAf7Llzo69Ot3VR3/wAPX59+vc0sbPA/S5teZhbm5hbd2g0O9F4c6O/ez8c9cLH/XO9u7cYHunh7uI5yXzrZ18vdp1+vXpaWfSzcbaxdrXv16mVlLpJJtGhvMwd334Xui/2Xmo1xD1ggIC4HNUzTZK6/6wKPIHcrt4Uq30XuPj6B/i4BgtvcxXNJkaIoHFlhMxOGsYOO9hu9WcXD0CSXAQYsw9WFcUxPg4b7qf/HMS0b7yw/7d1Yh69vmicWMM3WsEaV3W/oOv5G/rd+Q22fKBXDrG7CMKn6Vgdv1xb8+780rY5xuBvpm7TB2MNtwNGzf1sGutnffTYnwvrNxekDmP/155/m1SEs8/veoksZQ9jxCcQe+N/mT0MYZqX9/5DE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_20_2_50_link_6 {
            get {
                return ResourceManager.GetString("IRB4600_20_2_50_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1llBVntG3ruBsS3D24u2uA4O4Ed3d3d3e3QHAIEFyCu7skuAf3O/eu88a47/18PcfKWnt/VlXn0A0EGsNiGMYPPsTlw2/lPzWrtGzVvkPxDu3adWifIWmNZp27tOrQvmCuTFlzZsqaN2uuHJmyZc2SNWuGpMW7te3arXOzgu2bdevauXHbDEkrdfutbasm5Zr1qtahTbP2BXPmzJYtT9ZmeXM3yZ0zZ87sWRxySkzdPFPpZh3aNevauVemX5t1aWmn7+punuNt3LlJy1bdm2Vv2s7ToWOz9u27df6ti71p466NZZLb7bbKJYbTGEYBfFiHAmM9NkJI/rNhs9Wwfh5gNZZtturtfPlhNWJFb+3fC5crlH58PrLnvhEeYkn+KuP2BPW+Mt4uOjdPjGSGUSeRYZxLlH3+ro/3f/z/uvH/fMzqe+RAjcUDD9yrvWlFp2SjipOLW4zqxQ1jYOH/pT3/S/9X7/+8NoZcp91wGjawGw6SZBd9K+4kCW6trbhF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_base_link {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1jlF1p1K33PqeOGXeMTrpju2Pbtm3btm11bNu2nY5t+3vW2nXH+O79eesZM3O+6+VGuiqdpGKYhmH85kNcPvw2fqhaoVnzNm0Ltm3dum2b1ImqNO7QsXnbNrmzps2QJW2GHBmyZk6bMUP6DBlSJyrYuVWnzh0a527TuHOnDvVbpU5UrnODVs0blmzcvVLblo3b5M6SJWPG7Bka58jWMFuWLFkypXfILtF08bRFG7dt3bhTh+5pSzfu2CyCuquLtY+3foeGzZp3aZypUWtP23aN27Tp3KFBx4hG9TvVl0Fut9smRwz/bRi58MFtc43y2Akh+SH7xQjD9q2vzUh9MUIv5/tvmxE98tIeXLxSpujTC1H2PDTCA80kb9Jsi1vrB/0fLlhjsw/MYhgxMxjG+fiZ5uz68vD3/68b/8+HaQw6cHNj7QO/+8YuaO5dj+YWNPulL2QY/fL+L+35X/q/av/n2Rg2XSx+5KI2kmAz4ik2ww5xUQTEQQ6Ijf6A2FQc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_1 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1ltBRXtK272l1wd3d3d3eCu7sT3CFAgru7u7u7e5Dgwd2Dc7+16rwx7ns/3/nGZM619q69d1V3H0gCxGJYLJZffInLl9/KD7WqtW7TsVPxTh06dOqYIclvLbp2a9OpY8FcmbLmzJQ1b9ZcOTJly5ola9YMSYr3aN+9R9cWBTu26NG9a5P2GZJU6dG0fZtm5Vv0rtGpXYuOBXPmzJYtT9YWeXM3y50zZ87sWRyyS3RdPFPpFp06tOjetXemii26tbbTd/U09/E26dqsdZueLbI37+Dp1LlFx449ujbtZm/epHsTmeR2u61yxHBqi6UAPrxTgb88NkJIfpg/2Gaxfh1otUwebNPb+fbLaokRdWsPLl+tVPrppci+h5bwUCPZm4w74tf/znj9qLl5sqSyWM4ntVguJsw+d8/nh7/+f93y/3z9+uUr1qnu7EO/Bm4obgyaU/zXrwYHjc6XSlgsgwr/L+37X/q/ev/ntbHIjdssDtyK20mSnRYDrGSn4tLa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_2 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ11uFVV1O73Wrt7H7pbuhspKQHpUEBCOiRFQAFJFQQRCWkkRbq7U0QQJKW7u1Pi+40x932e794/7/k973nfMdZcc80Vex+Qc44Oy+FwvONDXD5CNp8a1G3foUvXCl07d+7aJXeGT9p0/7JD1y6li+YtUCRvgRIFihbOW7BA/gIFcmeo0LNTj57d25Tu0qZnj+4tOuXOULtny04dWlVr07t+145tupQuUqRgweIF2pQo1qpYkSJFCuV3y1ES6+R5K7fp2rlNj+6989Zo82V7F31vL3OcQIvurdp36NWmUOvO/q7d2nTp0rN7yy9drVv0aCGDfD6fLUuMZXM4SuHfdy01wu8kROWT+5nbYb8aYDtePnXr6fz3znYkiZ/alaPHa1a+eSRh61VH7Fsr04M861M3ec327fGxxWsw4ZjiDsfhtIWmbX5x9d3/rzv+nw/LsW1b4UJJd965sapiu2vOio3b965gffCgosMxsOz/0tb/pf+r93/ujUNO/CNHNSa0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_3 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luFVltIV3dx06pUG6U7pTuhRJ6U4p6e7u7k5FQFq6u0ukuzvuO+e3f9zn/rznfQZjzLm+WmvvA4KHg8VqsVi+8SEuHwEbP9Su1qJlu/Yl2rdt275dpuS1mnbq3LJ9u0J5smTPnSV7/ux5cmXJkT1b9uyZkpfo2qZL105NC7Vr2rVLp0ZtMiWv0rVxm5ZNKjTtUaN966btCuXOnSNHvuxN8+dtkjd37tw5szlll9i6eJYyTdu3bdqlU48slZp2buGg7+5m9vE16tSkRctuTXP+2tbbvkPTdu26dmrc2fFroy6NZJDH47HJESPpLJaC+OD2BUd57YSw/GBv4rLYPva1Wd41duntfPpms8SJ3trtsxd+LPPgTMzOO5bIQGvK55m3JK73mes7o2Pz3c9lsezLY7GcTppzzvb3d779f93yfz6+FflSwmq5vmdvi5Mlf2q+u6TV8rB4wQv3S1os/Yr8L+38X/o/veiHTeWwWMFmsZMEp9ZW3Hw4LS7wIzf4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_4 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1jtGXJ1m23vfdJnbRt27Zt27Zt26xK27ZtVdq28fU547zWvvd+vuxt1BgxV2hFrFO3btFitVgsf/klLr8CNn5To3LLVu07FOnQrl2H9mkTVm/WuUurDu3zZU+fKVv6TLkyZc+aPnOmjJkypU1YpFvbrt06N8vXvlm3rp0btU2bsGK3xm1bNSnTrFfVDm2atc+XLVvmzDkzNcuVo0mObNmyZcnolFWi6uTpSzTr0K5Z18690pdr1qWlg7q7u1nH16hzk5atujfL0rSdt0PHZu3bd+vcuIujaaOujaSTx+OxyRYjpbBY8uLDOuQd67UTwuQ3i05YLbYfA2yWaSfMC/38a7NEi3i1R5evlS/x/FLkfY8tkYZYE79LtyNO3V88rxfRN2feSBZLxygWy8V4Webv+fb47/+vW/6fX3//XVnUahl+8O+/F4taZ+4tarEMLGyd+US8wP/Svv+l/6v2f+7GIi/utLgtDnBaXCTJHosdHGSPZi/9bLiHJPi0bcOt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_5 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJx1WFXbt7D33uzE7u4ubAUVu7tbsLAVuxW7u7sVu1sEG1sUO1AURMRCRUERvneMfe7z3O/78/M9r2PMWHPNtdaYnHPPPT8NRoPBkMwvifIrpYnfOrTu13+Ibx3fwYN9h5TM295n+Ij+vkM8K7mVrehW1qNspQpu5cqWKVu2ZN46owaNHDXcx3OIz6iRw3sMKpm35aieg/r3auIzrq3vQJ8hnhUrlivnXtbHo3KvyhUrVixfxiJ3yaCLuzXw8R3sM3L4OLdmPiP6mem3jXbex7XH8F79+o/2Kd97sMN3qM+QIaOG9xxh7t1jZA+ZZLfbTbLFtEUMhmrEmb7VFjhcSNLIb39+GQymP34mw5dfzsf5m2wyZPzv0SIePmneIDo0XVCkIe10Y/5vpc7k6JrI+Mn/5roXczUY9qcwGB7kKr/pfHxk8v9vNPw/v5KDAuoaDeMv/Xz+sK5xylXJa6f0iahrMEyp8b8M+l/+X33/820M8uBVeeyxMI7MGauQVSXW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_6 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB4600_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB4600_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1jlCXrsrVzIRczF9u2bdu2bdu2bdu2bdvmbtv+njeqftzvjnHrOZFzxox4M7Oqz+jdu7U1i6Zp//hQqj4MK5dqlVq0bNe+cPu2bdu3S5OgWtNOnVu2b5c3W7qMOflfppxZ02XMkCFjmgSFu7bp0rVT07ztmnbt0qlhmzQJKnRt1KZl49JNe1Zp37ppu7xZs2bKlCNj05zZG2fPmjVr5gy6ekhY7p2ueNP2bZt26dQzXdmmnVvYyZ3dIh7jadipcYuW3ZpmbtLW3b5D03btunZq1NnepGGXhmrJ5XJZ1RsGkmtaHnRixzJj3DaMX13yTLZp1p/9rVqGyTb5bH79s2pRIj+zJ1eulyv+4nJw/1MtMNiS6H3anbHr/Gb+fVLEbo6U0TVteFjTLsXNPG/v96f//i9d37pFiduFNx8YfmhEgrhvDxSot6ukYW0w8MChNp/2vvnxpID2vz7yTz1xuNqiAYdTtT20u2PCkYXxhRfaqhbWtAH5/0ft/x/1/2Xq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_0 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1juCTJt+/xzCwjUZXVtm3btjFt27Zt27Zt2562bfN+I3penHue5/Tnrly/WBGZu2rv/+menu7ZV1EVRfnDD9HFj6DGpWrFZs3btC3UtnXrtm1Sx6/auEPH5m3b5MmaNkMO/l/GHFnSZkifPkPq+IU6t+rUuUPjPG0ad+7UoX6r1PHLd27QqnnDUo27V27bsnGbPFmyZMyYPUPjHNkaZsuSJUum9C7xQWz57LTFGrdt3bhTh+5pyzTu2MzJ3NPl74fx1+/QsFnzLo0zNWrta9uucZs2nTs06OhsVL9TfXHI6/Vq4hVayRQlN318+9KjfA6CKS5nrzoU7XtfTTl41SHfzY8/mhL57509vHS1bLFnF0N7HynWQDXh2zTbY9X6yf7I/85mjx9DUYbZinIhTqY5u78++vN/9TTBQsUql1uxb937SPzorrf5s0eN/6LF8Lj7c99a835wzKgFlP/1Q1UGHRw7ufbBN+liFFL3bSj0+8DcQvP7pS+sKP3y/Y/a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_1 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1zuBxZv/bxYle1q3vHtm3bNia2bXNi27Zt27ZtY+Lk/a6188d5z3WdfM7q+16/VVXde0+ezMzzzOQoqqIof/ghUvzwabxUq9S8Rdt2hdu1adOubZoE1Zp07NSiXdu82dJlzMn/ZcqZNV3GDBkypklQuEvrzl06NsnbtkmXzh0btE6ToEKXhq1bNCrdpEeVdq2atM2bNWumTDkyNsmZvVH2rFmzZs5gijeJkM9OV7xJuzZNOnfska5sk07NDeZW18i38TTo2Kh5i65NMjdu427Xvknbtl06NuxkNG7QuYG4yLZtTXxCJ7mi5CHHdygzyq1TguLl6nRd0b7305ST03X51fz4oylR/n5ljy5dLVf8+cXQ3seKM0hN9C7t9ti1f3I+8e+1OfpFV5RhEYpyIW7mObu/Pv7zf2X/3NsulD07f5/4to0cEq9gk+sjrieKNWqfeMgo9sr/+vF2vbdQtOszD2bdtb7wzuGzC8//UueA6uwsoij98/+Ptfd/rP9v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_2 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1j+CvLvu79TrrTSac76CTDtm3btm3bnMO2bdu2bdu2+XyrxnpxnnNdZ35O5b7rV5VO/mudPffk2IpDUZS//CZS/GY5ealasXmLtu0KtWvTpl3b1PGrNunYqUW7tnmyps2Qg/+XMUeWtBnSp8+QOn6hLq07d+nYJE/bJl06d2zQOnX88l0atm7RqFSTHpXbtWrSNk+WLBkzZs/QJEe2RtmyZMmSKb1LfEhYPjttsSbt2jTp3LFH2jJNOjXXmLu7/vsYb4OOjZq36NokU+M2Rrv2Tdq27dKxYSetcYPODcQlj8fjFN8wmExRcpPjO5QeZaiUgHhZr2uK80c/p7JY1+RP8/OvU4n87yd7dOlq2WLPL9p7HyvBgY6E79Jsj1X7F+dt/nc3e/UYijI0rCgX4mSas/vb47//r9zycEqyvkPX7vNOKtk+3chr+aunN6JHf9t1X8/Jtw4k7vglv/J//RY4vHffoExRDqYbMKtw9Kdq4e4TehT6e+dqYUXpn+// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_3 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1ztCTZtrfhQDoiMhJl27Zt267aZdcu27Zt27Zt27b9vWtV/3G/O8at586cvzXXCuQ+Y/TpPl3dV1EVRfnLL9HFL1Pjo1ql5i3ativcrk2bdm3TJKgW0bFTi3Zt82ZLlzEn/5cpZ9Z0GTNkyJgmQeHOrSM7d4zI2zaic2THhq3TJKjQuVHrFo1LR3Sv0q5VRNu8WbNmypQjY0TO7I2zZ82aNXMGp3hIWN47XfGIdm0iIjt2T1c2olNzB3N3l3+P8TXs2Lh5iy4RmZu08bZrH9G2beeOjTo5mjSMbCgOeTweTbxhILmi5KGP71BmlFcn2OLj61Zd0X701ZSXW3X5bX7+1ZQo/32zR5euliv+/GJw72MlMFBN9C7t9th1frG/8b+zOWpFV5ShYUW5EDfznN3fHv/9v7o4nGxIvP3+qfVH9vSsKiDWGVinbevLtnz71gLK//r1MP/vwqrvzoHP2rYiZZfNKBKpvig0ss+5IorSL///qL3/o/6/mfiPR95I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_4 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1j1ORat7aTqlRSVUklqbZt27Zt62nbtm3btm1rt927bdvftVbvH+c7Y5znemfmPe8518pK9R5vu6OoiqL84Utk8WV5uFSr1LxF23aF27Vp065tmgTVIjp2atGubd5s6TLm5H+ZcmZNlzFDhoxpEhTu0rpzl44RedtGdOncsWHrNAkqdGnUukXj0hE9qrRrFdE2b9asmTLlyBiRM3vj7FmzZs2cwSduElnuna54RLs2EZ079khXNqJTcw3f6Pr3NsGGHRs3b9E1InOTNoF27SPatu3SsVEnrUnDzg3FkN/v94gTuskVJQ95QocyowNehCMuxW94FM/3fh4l9w2PfJoffzxKlP+e7OGlq+WKP7sY3vdIcQepid6m3RG7zk/63v9mc3wPK8rwyIpyIW7muXu+Pvrzf2U5/bby/qTb+ify9OlWIFWxKxmLPCu5/+i7Pu0KvW5XQPlfX1+eDCqiKkMP/im+s0jw2rQiitK/kJrjrMj5/0fs+x/x/3nim0du [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_5 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ1luNzIkm0lFamqVFKZmZmZmZmZmZmZ7TYzMzMzM7WpzdjmNjMzvBXp82PefN+cNaHYuSMyJWXVHd/uazs1XdO03/xIlh/L4FK9cstW7TsU6dCuXYf2aRNWb9a5S6sO7fNlT58pF/+XOVe29JkyZsyUNmGRbm27duvcLF/7Zt26dm7UNm3Cit0at23VpEyzXlU7tGnWPl+2bJkz58zULFeOJjmyZcuWJaNHbhJFrZ2+RLMO7Zp17dwrfblmXVq68X3d/9wm0Khzk5atujfL0rSdv0PHZu3bd+vcuIu7aaOujaTJNE1DnjCcQtPykid2KjvG70I4cimQ29CMbwMMLUtuQ73N99+GFjXizR5culq+xNOLkfY/1MJD9MRv0u2MU/cH9e+5/vTmfBTWtOFRNO1CvCzz9n55+Pv/yrkXLykbr3yVAw9Lxbu/oHmPgmYLo8+4d/UPFP1nyM4RHTsU1P7Xz+/fU4vqWu9Dl7rvKaofmCe6cFr/6aKaNrDA/4j9 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB4600_X_2_05_link_6 {
            get {
                return ResourceManager.GetString("IRB4600_X_2_05_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJxleBVLs7ZH1hpbuLNxd3cJ7u7B3SVAggUSYKMbd5fgTpBAkOAOwS14CBIkwYL7d3cnP853rutwv7Xqqerqnple2bxheqYVVVGUv/wRXvxJpPHRqlnvPj4Dqw8cMGCgT8GsrXr4+vUZ6ONVunCxcvyveLlShYsVLVqsYNbqQ/sPGerbw8unx9Ahvl36F8zaZGjX/n261e/h32Jgvx4+XqVKFS9etliPcmW6lSlVqlSJom5xkJRy7MK1ewwc0GOIr3/hhj38ervIm8PiD+N08e3Wu8+wHiW6D7AHDurh4zPUt6ufq3uXIV1EkWVZmjjDZHkUpSJ+zuAG020dkVR8dPdWFe3HGE1p7R1/PT//akqqhCt7djOiUe1XN5Iffa4kG69mf1/oQIb2v2jPmlBbtp1HUdpj1zOVWHn42/O//5dvvnhk95g5c45NbdFp+sCz+6qkHhHZV8k699iZdX0zzM5yoYryv/6cWlbqlDr29MmRe6dvV5VL1dHVVWVHdUUZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_0 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1z1CTLlvfxLGQxqzKr2rZt27aNp20bp23btm3btm1b73dH9x/zzlrTn4nav9gRGZWZz1333KMezaZp2h9+SZVfhp2PqhWbNW/TtlDb1q3btkkdv2pEh47N27bJkzVthhz8X8YcWdJmSJ8+Q+r4hTq36tS5Q0SeNhGdO3Vo0Cp1/PKdG7Zq3qhURPfKbVtGtMmTJUvGjNkzROTI1ihblixZMqXX5UsiqbPTFoto2zqiU4fuactEdGzmpO/u8vdrfA06NGrWvEtEpsatvW3bRbRp07lDw47Oxg06NZBNHo/HLndoJdO03NRx7UuP9DoIpnwciO/Q7N/72rUt8R3qaX78sWuR/z3Zw4tXyhZ7diG055FmDbAlfJtmW6zaP1nv+29v9q5RNW1oJE07HyfT7F1fH/35v6p3i/fc3l/T9mb7Um/U+iZb8u+N17l0RJrpexeW6poz9bJr+bX/9eu689OB2P0fHPjdp0qhuwODhZPvOVDo3b5+hTWtX77/Mfb8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_1 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dJ0DlCVbs61zK7dRbdu2bdtWNU7btm3btm3btm3rfhHVb4z73hivvxs5Z8wVa2XmPjX+vt2nuo9hMQzjLz9E5YfPyqVapeYt2rQt3LZ167Zt0iSoFt6hY4u2bfJmS5cxJ/+XKWfWdBkzZMiYJkHhzq06de4QnrdNeOdOHRq2SpOgQudGrVo0Lh3evUrbluFt8mbNmilTjozhObM3zp41a9bMGRxyk8h6drri4W1bh3fq0D1d2fCOze3kzi4Rt/E07NC4eYsu4ZmbtHa3bRfepk3nDo062ps07NRQhlwul1WeMJTcMPKg49uXGeW2YYJyefvUalh/9LUaD59a9W1+/rUaUf692aNLV8sVf34xbO9jIzTQkuhd2u2x6/xifeW/2Ry9oxrGsMiGcSFu5jm7vz3++//Tfg1+1c58a9i+5nsnL6nqOFfg//SPHWcarW34tIDx//z4+/dYIcu+6weXro5ZZERWs4jFqFHQksBT1DD65f9ftfd/1f+VyT8ePSji [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_2 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1llNvIl/dxWbKMkm0ZwszMzMzMzB1mZoYJT5iZmZmZmXHCzMx5vlXJi332nO3PXt9f3SrJds+Z3kn+nY5iUxTlNx+iiw9D5aFapeYt2rYr3K5Nm3Zt0ySoFtWxU4t2bfNmS5cxJ/+XKWfWdBkzZMiYJkHhLq07d+kYlbdtVJfOHRu2TpOgQpdGrVs0Lh3Vo0q7VlFt82bNmilTjoxRObM3zp41a9bMGXTxJCF573TFo9q1iercsUe6slGdmtuZO7v+eRpPw46Nm7foGpW5SRt3u/ZRbdt26diok71Jw84NxSGXy6WKVxhIrih56OM6lBnl1gh+8ZAkk6qo3/qpSoxMqnw333+rSvjvO3tw8Uq54k8vWHseKoFBtkRv0m6LXecH+3cy/jmbY1VEUV4FFOV83Myzd315+Pv/6ke3Nalfs3ivvUl/d8q89938ApG2JWxjT/TeO7BG9EyZ6u4roPyvj2nT9hW07R11oMGOJ0WOz3IXmdZxWeF9l2IUVZT+ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_3 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN1juCPbt+/xSkWVpILKatu2bdu2bfdu27Zt27Zt27bud8zuF+ee5znrc2fGb46JVFbfZ+//bh3NpmnaH76kypep81KlQrPmbdoWbNu6dds2qeJVadyhY/O2bXJnSZM+O/8vQ/bMadKnS5c+VbyCnVt16tyhce42jTt36lC/Vap45To3aNW8YcnG3Su1bdm4Te7MmTNkyJa+cfasDbNmzpw5YzqnvEmEujtN0cZtWzfu1KF7mtKNOzZz0Hd3+fs23vodGjZr3qVxxkatPW3bNW7TpnOHBh0djep3qi+bDMPQ5QlDSTUtF3Vc+1IjPXZCUF72O+ya/r2Prm122NWn+fFH1yL9+2QPL14pU/TZBWvPIy00wJbgbeptMWv9ZL33v73ZVkbRtKERmnY+dsbZu74++vN/1VuzOx1rmmvu3vrzPPs6dVmYL+2qLru/fuq3N+eFt6syR1+dT/tfX/tmegrZ9mY5sPOqo/DlPX/IqQveWBK5sKb1zfs/xp7/Mf6/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_4 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lLx1WFXd1+6/aq+9TQwURbELCxFBERALMEEMVBAQsUFEUAkJG4OwUSQUbAUTaVEJAwSVEhUDEJQQaSR/95w+f5zfea9zruv4ecYe97zHmHOvvXmu9/ssGetlWIZhOvCHZPKnK4cXk6Wbt9htn7N927btduOHmGxwcNyy3U5HY6KqJv6ZrKk+UXXSJNXxQ+bsst25y2GDjt2GXTsdrGzHD1mya53tFuuFG1yWb7fZYKejrj558jTVDZpTraeqq6urTZKQN+lNz55osGH7tg07HVwmLt7guFmAL9397206WzlYb96ye4Pa+m2dtttvsLPb5bDOUVhvtdOKNMlkMo5cYY/RDKONfHLHIu9OPIQceTFuZxiu2ZNj9Nr/fZqWDo6R/++TFWfnGRr8yuqZ+IPpcYAd9mdCzIA1rah3+693mpOMYRYh3iupBSc0/ej4P+Ujj+s0NUJdnr5/eeNJncfemXX/rdXmKQQyf7xnMv/bn7MmX+eyzJPnHXmiHnuP1WOZ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_5 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dNwHWBRJ1zj67p5RVlEQERBJIigiSUEkg4iKioiKJEUyopIEJAxIUHLOkkFBQIkikpOBLMFAlJwlS85wT8++333e//e/l9/W1KlT1T3TPaPMqd1nERRBkB34wXv8Zx8GD6q3Hz4yM5czNzU1N+M9qmpoafXI3EzqHP8ZMfhHUEyY/8zp02d4j8pZmzy1tjSUMjO0fmqpa8J79Ka1nskjfQVD0h1zY0MzKWFhQUHRM4ZiIvoiwsLCQqd34U9CSz43v7yhuanhU0sSv6Kh1UMi5Cls/n2avbqW+g8f2RgKGZjuMX9iaGZmbalnRTTQfaqLL/rnn38w/BUe4EIQSeiDLa777SFAQI0/tDxAEGzdGUNqH/x7NRs7GHLoP1c23NJ+Q378F03FCHLAFT32l6+ISXMT5oP+s1Z0BF6GOLSfLELxZasjO/9/fesbQpzsiv4nQ4NapUlBl/O0zN7/cE6ofxIutnaqHNA4j/yvn51s9BL7rZovOzu7L6EIEY8voC60 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IRB6650_125_3_2_link_6 {
            get {
                return ResourceManager.GetString("IRB6650_125_3_2_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Movement_Icon {
            get {
                object obj = ResourceManager.GetObject("Movement_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Movement_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Movement_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Naming_Icon {
            get {
                object obj = ResourceManager.GetObject("Naming_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PathGen_Icon {
            get {
                object obj = ResourceManager.GetObject("PathGen_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PathGen_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("PathGen_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Plane_Visualizer_Icon {
            get {
                object obj = ResourceManager.GetObject("Plane_Visualizer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RAPID_Icon {
            get {
                object obj = ResourceManager.GetObject("RAPID_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReadDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("ReadDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remote_OFF_Icon {
            get {
                object obj = ResourceManager.GetObject("Remote_OFF_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remote_ON_Icon {
            get {
                object obj = ResourceManager.GetObject("Remote_ON_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RobotInfo_Icon {
            get {
                object obj = ResourceManager.GetObject("RobotInfo_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RobotInfo_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("RobotInfo_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SetDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("SetDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SetDigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("SetDigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpeedData_Icon {
            get {
                object obj = ResourceManager.GetObject("SpeedData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpeedData_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("SpeedData_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Visualizer_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Visualizer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timer_Icon {
            get {
                object obj = ResourceManager.GetObject("Timer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timer_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Timer_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tool_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Tool_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToolData_Icon {
            get {
                object obj = ResourceManager.GetObject("ToolData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToolPlane_Icon {
            get {
                object obj = ResourceManager.GetObject("ToolPlane_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WaitDI_Icon {
            get {
                object obj = ResourceManager.GetObject("WaitDI_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WaitDI_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("WaitDI_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
