//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotComponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotComponents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Auto_Icon {
            get {
                object obj = ResourceManager.GetObject("Auto_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Auto_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Auto_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChangeTool_Icon {
            get {
                object obj = ResourceManager.GetObject("ChangeTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChangeTool_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("ChangeTool_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CodeLine_Icon {
            get {
                object obj = ResourceManager.GetObject("CodeLine_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CodeLine_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("CodeLine_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_Icon {
            get {
                object obj = ResourceManager.GetObject("Comment_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Comment_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Comment_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructMovement_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructMovement_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructRobotInfoComponent_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructRobotInfoComponent_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructRobotTool_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructRobotTool_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructSpeedData_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructSpeedData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DeconstructTarget_Icon {
            get {
                object obj = ResourceManager.GetObject("DeconstructTarget_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("DigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DigitalOutput_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("DigitalOutput_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExternalLinearAxis_Icon {
            get {
                object obj = ResourceManager.GetObject("ExternalLinearAxis_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExternalLinearAxis_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("ExternalLinearAxis_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlane_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlane_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlaneX_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlaneX_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipPlaneY_Icon {
            get {
                object obj = ResourceManager.GetObject("FlipPlaneY_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ForwardKinematics_Icon {
            get {
                object obj = ResourceManager.GetObject("ForwardKinematics_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetAxisValues_Icon {
            get {
                object obj = ResourceManager.GetObject("GetAxisValues_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetController_Icon {
            get {
                object obj = ResourceManager.GetObject("GetController_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("GetDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GetDigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("GetDigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Info_Icon {
            get {
                object obj = ResourceManager.GetObject("Info_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InverseKinematics_Icon {
            get {
                object obj = ResourceManager.GetObject("InverseKinematics_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1nmBRFtIZnunt6pqdneshBSZIkSc4ZySA555xzVJKI5CCgKCA5ZwREguSMAiIoklFQlKASTQjCfc/p/XGf+/PyPh/fV6erq6qre2d32VkNBAOBwAv+iMufmMFfzRp279G3X+V+ffr065svS9MuAwf16Ne3XPH8hYrlL1SqUPGi+QsXKlioUL4slYf0HjxkYJdyfbsMGTywQ+98WeoP6di7R6faXYY17terS99yxYoVLlyyUJdSJTqVKFasWJGCIZklpQ6ev3qXfn26DB44LH+dLoO6W9TDQ/15oh0GdureY2iXIp37OP36d+nbd8jAjoOszh0Gd5BOkUjEkCUmezUQKIuP71d2mmMSEvJXyzlGwPh3tBGoO8fQy3n6wgikSrq0m+cu1K1+59vk+38OJBsbzPrgtc9fbv2M42mS+pYMvxQIHETfZCyyaO8/P7/4/3rg//wJHihzuEOOe4fcs9Za/HVnw6PXg4GelQOBdyr8L+3/X/o/taQ//jqDuBEw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_base_link {
            get {
                return ResourceManager.GetString("irb1200_5_90_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_5_90_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_5_90_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1l2NRWtIVnMpPJTJKhSEtxd3d3K9oChUILxV2LFnd3CqVoKVLcrTiF4hT3FneXYkUK99078+M+9+flfRZrnZ3k5OTkJJ8AHz6/z+f7wC9x+eUa/FanZqvWHTqW7di+fccO2VJ91bxzl9YdOxQvkCN3/hy5C+cukC9Hnty5cufOlqpst3Zdu3VuXrxD825dOzduly1V9W5N2rVuWqV5z1od2zbvUDx//jx5CuVuXrhg04L58+fPm8uUsyTQznN81rxj++ZdO/fMUa15l1ZB6lZ37zx2485NW7Xu3jxvs/aRjt8179ChW+cmXYLNGndtLDuFw2FDhhg3o89XDB/asdiYSIDwkfxW5pHhM970N3wFHhl6OW8/GL6PY5d249TZzz+7ezLejpu+uIP9aZ5k35S0/ju2v3/o7VvITuLz9Uvm851Invfnbf/e/PD/dd//+VVv/qtd88obf8zLVbys32eVJZddXOBJWZ9vQMn/pR3/S/+nFvvljdOPG74ACoKJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_1 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBXlF7dn9uTeQ5eUIAoCgjRIN9Ld3d0N0iBSKt0KAiKiCKLSpaSKYICKgQoSf0CQEEHyvdd69of3ej++577W+f3WmplnOp599t7Hsi3LesyPqPykiPGrZZNevQcMrDawf/+BAwo+1aL7kKG9Bw6oUKpQ0ZKFipYpWqpEoWJFixQtWvCpasP7DRs+pHuFAd2HDxvSuV/BpxoN79Kvd9e63Uc3G9i3+4AKJUsWK1a6aPcyL3R9oWTJksWLeDKX9Np4oZrdB/bvPmzI6EL1uw/t5VIPRpj5JDoP6dqr94juxbv1jw8c1H3AgOFDugx1u3Ue1llGCsMwJouYJq9llUenDiz/atzBpJZfbbK7VuzehJjVILurq3P/cczKkFy1cyd/bFDz0om0+85baabYT19/fke2dg8Ynik5buntuSzr3XyW9d2TxVfsuXv+8f+vWv/Pj22t3v+ydWX/V1+9Vc22lle1rStVn7rdvbplTaz0f8W+/yv+n1ryJ5ZsLgYO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_2 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1l2BVVuIb37JqZvWfvj+7u7u7u7u5O6ZRQEWlQRBEkRLpEuhtpEBCkBWkBAQGRPPf7zv5xrvPzfPf18DzrnTVrrYkdX+IxPB7PBz7E5cPx8k/TBt269+lbsW/v3n375ErXpHP/Ad379ildJE/+wnnyF89fpFCeAvnz5c+fK13FQb0GDurfuXSfzoMG9m/fK1e6eoM69OresWbnYY369uzcp3ThwgUKFMvfuXjRjkULFy5cMF9AZkmog+ep2rlv784D+w/LU7vzgG5+6uZgd55Q+/4du3Uf3Llgp95234869+kzqH+HAf5O7Qe2l06WZXllifGyejyl8HF9S022fYQ4+efYGK/H+3q017N7jFcP580HrydR7NBunbtQp+r9s/F33/bE+9TI8CT31pSt3rJ9fKxvsRRJPJ4cST2eM6kLztv56vaH/697/s/HgzsL9xmexft6jS9fySg3vaLhWVfhk9v9K3k8Y8r+L+3+X/o/tdiHu04Dl+QjSfZ7AuAl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_3 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ112BXVG66nY0t3d3d3pzQSioS0SreAICkhKSjSJYIgIC2gNMJPARUpCekGEeQDRBQ49/vO/uNc58/DfT08z3r37DUza9bMnu9j741hGobxkj/i8ieRxV9vNHu3W+8+Nfv06tWnd6Fsr3ftP6Bbn96VyxQpXrpI8fLFy5QqUqJ4seLFC2WrOajnwEH9u1bu3XXQwP4dexbK1nRQp57dOjfoOrRFnx5de1cuXbpEiXLFu5Yv27ls6dKlSxZzZS0ptfMidbv26dV1YP+hRRp1HfCuQ91/L1pPrGP/zu92e69ryS69wj59u/buPah/pwFOl44DO8pCQRBYsonJ8hpGJXxcn0pTQpuQVP769FvfsJ6NtIyJBPnz70vLSBXftWsnfmtc9/bx5LuvG8nGmjkeFN6ese1/PN40vmy5RuUNY8FrhnEsc8lFO59ef/n/68b/8+fl7nE1T1zosS/TpCa16lV/VtM0etYwqw2oZRijqv5f2v1/6f+pxf9Y+reJS7JJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_4 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ133I9l2MbvPX7DSmb23iN7z5REisree2ZvSiIpZJYkQlMlCtl7hGSPpISyE7J5v+d5P3+8n/fP1/dzOI7rvK77uq/7un/jeR6/pwzTMIxH/BGXPwmLv15+oWu33n1q9+nVq0/vojlf6tSvf7c+vauWK16qbPFSFUuVK1O8dKmSpUoVzVl7YM8BA/t1qtq708AB/dr1LJrz+YHte3br8GynoU369OjUu2rZsqVLVyjVqWL5DuXLli37ZElXzvKYTl68Xqc+vToN6De0+HOd+nd1qPuDovPE2vXr0LXboE5PduwV9unbqXfvgf3a93c6thvQTgYFQWDJEtMUMIwq+Lg+VSaFNiG1/FX/imlYd0dbRrUr0QXde2QZ6VMu7czBIw3rnT+Qdv1ZI81YM/c/xVZlbXmffi9lbIXfMhhG2ccNY3+2Jz9ae/vso/+vG//nz5gZW2tvuWlu+j32Qh3TcOp06Vy81uXXutehp/r/0vr/pf9TS/lj6d9cItjaFne0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_5 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp5NJVt+O+f/agUFRlSKTKUBpFkyrArlUaSJJmSkAzbkHkqEr1IJUMZizIThcwp85jKmBAbITZ2bON2rnt7f7/1O791zlpnnbXOX8f1eb/7+u77ue/rvp5n33u1e1cYAcOwJQiUUazH4UXr0i0zK5IyydKSZCW684qxrZ0ZyUpRWkxCSkxCTkL6sNghiYMSEqI7le0t7tjbGitaGdvfsTW0EN150f6GhZnROWPnyyRzYytFKalDh2QljOVkjGSkpKQkD65Gu3AyioupGJMsje/YOotdMLa7tQrGmR2W92ExtDW6ZeZgLHnTch3J2tjKyt72ht2qm4Z3DNGktWvX4qhFdhEMU4DsQ1IIWMcEhg29RIljGD7niWNPxJdvZ34Jx7j+vTXy91ZVlaFvm0r6MXZvguD4gTxe3QW4rv3vXNkmKHwZ9HWHZHTRTP/S/23G/lssLTGdIGCxpdYXtE8Qjq5G/pjWKaMTGHaX+F9U8l/0P439x2eD4YxXAmTkmMAh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_5_90_link_6 {
            get {
                return ResourceManager.GetString("irb1200_5_90_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_7_70_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_7_70_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBRHtLVnerqnp0dwd3eHg7sFDe4QggaH4BYCwSG4BbfgEBwCBBICBA3uTiC4O8G+d++eH/e7Py/vs7JW7a6qrq7uMxyZQzxej8fzmT/i8ids8J86tdu179K1XNfOnbt2yZGmfpvuPdp37VIiJlfeXPnz8CdX3kI50pTr1alnr+5tSnRp06tn9xadcqSp2atlp/atqrbpV7drxzb0jsmXr3DeNkUKtSoUExOTP48lZ4ivE+f6ok3Xzm16du+Xq3qbHu1M6nZv9xzBFt1btWvfu03+1p2drt3adOnSq3vLHmbrFj1bSKdAIGDI8uJk9nhklLPfCjs+Qmz5j3nZ6zH++97wfLjk9bz/bHgSULx1+tyXX9w7Fff3fz1xhnrTPc25LXnTDxw7Tp+YpAk9nt3JPJ6TKfPP2/n238//V/f8rz/eP4rtSZ/x8Z8fj5sr8LIFVz8v6/F0KOfxDC71P/T7/9D/V5P7oRMZ7nS44fFxya5bJBP3kwS/x1b8ngA4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_base_link {
            get {
                return ResourceManager.GetString("irb1200_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1200_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1200_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ112BVV2O5n7z17z549Q4d0h0g3Snd3SHdKSokSAiJdSkqIiiIgIqBIiSBKh6SAgHR3N3y/51n7XNd3zp+H33V73+uZmTVr1qyZN4T3tQKWZb3mj7j88YP8p2GDrt169a7Yu2fP3r3yZGrSqW+/br17lS6ar2C+wgX4k69g8TyZKg7o0X9A306le3Ua0L9vux55MtUb0L5Htw41O33YqHf3TuxdtFChEgU7vV28Q/GiRYsWLhCWMyTTjvNV7dS7Z6f+fT/MV7tTv642dWegOUesXd8OXbsN7FS4Y0+3d59OvXoN6Nu+n92xXf92slM0Gg3K8BLntCw5yt0e9t0QIZH8p0i2oBV89nHQykN4/jpoJad44fDROlWvHkqy6aKV+JNAljt516Vt+YJtFvsUfZnCsoals6yD6Qt/ufHJxdf/v279P396f/t4y4rKwT+/LVC6IsOuSK64uNgd8vCy/0ub/pf+r5rcD+0oqP8N4EErhGwIowiEqUjbsaKWC44V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_1 {
            get {
                return ResourceManager.GetString("irb1200_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nL1nuNRUG7adZCbJTGboHUGqIAoIKIIoKiKgICAgvXdQAemiFOm9995770W6NJFeVUC6gMAjIh2E77zvNT/e73j/vZzHta9r3UlWVjIlZfYeLNuyrBf8E5d/cYcfVSq3aNm6Tck2rVq1aZ03a7Wm7dq3bNO6eOH8BfO/WYB/+QsWyZu1ZMevO3Rs17R466YdO7Rr+HXerJ93bPR1y8blmnb5os1XTZm7cKFCRQs2fadI4yKFCxd+s4Ara0ilHecv07RNq6Yd2nXJX75p+xZh6n4ns46gYbvGLVp2avpmk1bRNt80bd26Y7tG7cNNGnZoKDNFIhFHhpc8t2XJUtG9bjwaIiSTH3NeCVnOkx6ONYXw9IVjpaZ45cTpCmVuHE+x7aqVvLed/U6+jS/Veca0b5in8IKXLeu7PJZ1LPOb07Y8uvri/9Wt/+vfrJ2NrZs7Dx6YUdKyJn9kWTc/ytSx/MeW9cMH/4e2/R/6/9Xk8dBuHP1p444VYpNtJWy5Stjy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_2 {
            get {
                return ResourceManager.GetString("irb1200_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nL13lBTVF7Zbnaq6qrvJIDmJEhQQEQEDiqj8AJEsICI556TknJGcJecsOeecc46SJUnOIHzP3qfvWt+9f9551sv7nl2nTp06VT0z3dMzWD7Lst7yIS4fUT//lCtbv0HTZkWaNWnSrOmHGX+q07JVg2ZNv8yXK0+uvB/xkStP/g8zFmnTuHWblnW+bFqnTeuWNRp/mLF0m5qNG9QqUadd+WaN6tA738cfF8hTp2D+Wvnz5cuX96OQHCGpDpyraJ1mTeq0btkuV8k6reoHqTu/mWN4NVrWqt/gtzp5azdxmzWv07Rpm5Y1WwVr12hdQzqFw2G/TC9RVsuSvdydoagbICSUf4LbfZb/ZRe/9Xqbz3r11m8lo3j12Mkfi948mnjjNStRD1/m+zlXp/nlNdsO0SffoySWlfwdyzqSLu/E9c+vvf3/69b/52NClc1bLGvGlrmJsn9rdf2iiGUt/SZvkarfWlbXr/4vbfy/9P+qyfXQgfz6L6el+KwABEnGQ1p1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_3 {
            get {
                return ResourceManager.GetString("irb1200_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ113BRl2LZnd6fnoVO6S7q7uzuVBkEJKRERFUEQKRERkEakpENEUhpRBJEU6RaQEmm+47pm/3i/98+X43dynvc1M/fUPbOzD/ssRsQwjJf8EZc/CVH+ata0R88+fav17d27b5/8WVp26z+gZ98+FUoULFKwWGH+FCxSKn+WaoN6DRzUv1uFPt0GDezfqVf+LI0Hde7Vs0u9bkOa932rG3OXKFq0dJFuZUp1KVWiRIlihS1ZQwrtuGCtbn17dxvYf0jBBt0G9DCpO++E6/A79e/So+c73Yp17e31fbtbnz6D+nceYHbtNLCTzOS6blQ2L2luw5ClvL1WghcjJJG/frpiGdEnH0aNjYSnL6NGSoqX/jjesNb1I8m2XTaSjohku1NgY/rXnjFtPPOUOFzMMDI3NYzfMxabveXR5Zf/Vzf+95+Pclc7duatHcn8UtWbVNlXzTB6Vb25rW11JlT6H9r2P/T/1eR8aD9R/TuCCxEjBiYpdEurjuEanuIaPgSk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_4 {
            get {
                return ResourceManager.GetString("irb1200_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luBRXsHbHe1rm4C7BIUBwC4GgQYK7Owd3twDB3S1okBCCQwjuLsHd3V1DCPKtqj4/7nd/Xtbz5q1du3b17t0zg51DPF6Px/OFH+Lyw/Hxn2pVW7Xu0LFEx/btO3bImqpmdJeurTt2KJw3W85suXPwI1vO/FlTlejerlv3LtGFO0R379alSbusqSp3b9qudbNy0b2rd2wbTXXeXLkK5Iz+Nn+z/Hnz5s2dIyhXiKeNs5WO7tg+uluX3tkqRHdtFSBv9HCvYTXp0qxV6x7RuZu3Nzt2iu7QoXuXpl0DzZt0ayJF4XDYJ9uLndHjkVXmgaBj+gliyX8etvd6fB8G+Dw3Cf774vPEJ3nnzPmKpR+ejrPjrif2YG+aF99sSlb/I3N/UZN3QRyPJ2sCj+dUitxzt72/++X/6p7/9WPA1Mkl9rz17r456tuSHs+5Ei1aZCv+xFuVeGCR/6Ed/0P/X06ehzby6X+5LfCjAPg9wZhxiEgIeQwl5AmDiSywkQMR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_5 {
            get {
                return ResourceManager.GetString("irb1200_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zp5VM7r++8/z5N2kgrZSoMMDYaUSrMKsZuIlCERpXnUoJEITdIgtgaaZGoXqQylydCgGZGQ5hnRrEm/9/3p+zvne9bvnLV+66x1/jrdr/3uej/Xfd/XfX2e535kr4ViUBQ1jUEiGfOZ+GGwx9rG0UnDycHByVFi+T4LF1cbJ0dVOUlpSdkNGJLSChLLNU7Yu51wsVB1tDjh5mJqL7F89wkze5tjuhZehk52FlgtJyOjKG2hpHBMQU5OTnYDKzmBhy4sqWnh5GDh5uIludPC1XoO8mzuM2fMM3U5Zm3jbiFr7sDudNzC0fGEi5nrHHNTN1OyaO7cuUzS3gJxiiK72EtZ57OzwHCTH7EiFMUcP82kImEmppnUYiTb333Q0+ypXVjYQS04x1j5c32OwKFJzFlijZw2ihlCb4Vk4/N/dUz/30bqv4w6DYpKfG5TtXkbdaae+C3GJTrbKOqM+r+p8N/0v+TI50GXYdI/GYhMigWPzKCZQ7HSzKH+AGzQXMAO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1200_link_6 {
            get {
                return ResourceManager.GetString("irb1200_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNp3XI9f/DD+s69RyJ7JSEYqlZaWyoqiiEgJLZSWrZQ9kxEqImWFrDIS5UOLJFS2rKRBpUJR6nfevvf9eNy/+8/7/XzUdfV2va/rnHOd65zX67wBCABo5y/FVvFSRvzXrOmLFvsH2AQsXRrgP3LALK/gZYsD/M0NtfW0dY1HGRpo6+qO0tcdOcBmhd/yFcFe5v5eK5YHL/AbOcBhxUK/xR5TvNY4Bfh6+ZsbGOjpGet6mRh5GBkYGOiPooqLdP13bu2JXgFLvZYHr9G291q2iPD3hZX/cxl5QbDHosUrvfQ9l0oBgV7+/iuCFy4jnguWL1AcJIoiUpRQZSgAZnxrvkiMkDDf6aT41bgLAPQnHIGKXf9Tm5Z2BLr9r5p9LnkxdWJVcec75UBlExz0XetmX9dW/u+X/texxn2UALCmABSp6h/LaC5v/3/dgv/rZTjwTlbh+qCsCT9n3YJgl015VpDNn/YRNgCst/w/fu78Hz//v/f+960B6N9vEShz3UAf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1660ID_base_link {
            get {
                return ResourceManager.GetString("irb1660ID_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB1660ID_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB1660ID_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxjmB1ZuCjgslbZuzZjd9KxOrY1sTq27Yk58cS2baNjJxPbtnm/6nN+3Of+vPU+tas6s6t2aa31LdRgOIZhf2Dyl/4kEvBRs1qr1h06Fu/Yvn3HDpljNZt36dq6Y4eE3HHZ4+LzZsudKy4+PluO+Myx4t3bdevepXlCh+bdu3VJbJc5VqV7k3atm5Zv3rtGx7bNOyTkypU9e9745vnyNM2TK1euHNlo/0eM5H3HlW7esX3zbl16x1Vs3rUVBf/O9vifnxESuzRt1bpH8xzN2vMdOzXv0KF7lyZdqWaJ3RL9L3EcR/hHqKbDsIKwTGjFjeVJWFH8j0efcYz4PpDArn3+n/P58YfAzP89s4eXrlQq/eyitu8Rpg7BU77NsiNY/yf89wX/+928aloM83QMuxDOMXfP10d//n+X2P8z/TGGHmKxVId+/PlarNPwOcWxQUWKr3uYugSGDSr8f837/q/5//m3/52I5E8SYwCPiZgCdMzFwiCGpcbSgyxYLiwf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_1 {
            get {
                return ResourceManager.GetString("irb1666ID_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNppOFVf2DDwPa89HSqhUmnUYMpQyFgqJCRRMhUpZIiQIaS5FCJJikRzKhUSKkqIQhnKTGhApkyh3uX/PB/e6/34rt91husc9rD22ve6770PgiII8g+2ydfJxmPwyWKLk7O7h66Hm5uHu8w8C0evA84e7pqr5BTlFFRXrFopp6CwQklBZp6uj6u3j5ejprujj7fXLleZeZt97F2dHQwd/bd67HN011y5UlFRVcFRTcVBZeXKlUoryMmViPy3bDk9Rw83R28vfzkjxwNOBPwc+P7PathdXg5Ozr6OSrvdGI/9ju7uPl72B4jdu7x3Tf4RTdPY5BZOWYIgGvBV04k+y+DwjfDk0/VLCIL9CcGQi5f+Z2/G/mHI9P/ds7bKGmO9H5+mvmxHphxFF/TKZklYj8Pvbf/3b1X3ChCkD27KxzlKCbkj7f/+f1+R/6d5DwWuFT186PXM6YW6uzE33WlIVX6k4Oo6BDms/X89Xv5fj//ns/9tkztOIijCQpPvKQhH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_2 {
            get {
                return ResourceManager.GetString("irb1666ID_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxlWFtZ1DDsuLsQd3cjngAJkBASCCTUddoydXf3Tn2m7u3U3XXq7m5Td/d26vounu/58V7vz2/dVxKuOId99l7rnL1BIBEIxC+ImtuaoKDgqnamVesOHQs7tm/fsYNZXru6S9fWHTuEPVan1eGze9xWh8Pucpjlhd3bdevepTrcobp7ty6/tTPLK7o3a9e6ebK6d1XHttUdwm630+lzVPu9zb1ut9tlx9Z8CPt/3tsar+7Yvrpbl97WsuqurTBwP77H//cxpN+6NG/Vuke1q0V7YsdO1R06dO/SrCumxW/dfqt5EoFAQNV8Q4YOgQjBbbgVYSwRDT/Qa642UHEI1NeBKMQS+KEmvv1CITj/+5s9uPhvefzpBeaehwjGUKTyjeUfUcPv8HiH/32uj9UNgTgA73te4pq76/PDX/9/bxH/T9S+hNyvwLzYf6Zh/6IPwycWdkPIC2f/XF2EQAzK/78ue/6vy/9z3/8G6n+usQgKYCP4CCnQIEwIJ/Ah8hEx [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_3 {
            get {
                return ResourceManager.GetString("irb1666ID_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxllBtHtCBgMTPziJkZRwwzI9kxMzMzO2bHEHPMzEwxM8TMjDHFzMwe23vH+368sz+3vtNqnZHULeiuureqehBIBALxE0rFuqJQUHBTs2rrNh07JTt16NCpo1les0XXbm06dYx4rU6rw2/3eqwOh93lMMuTPdp379G1RaRjix7duzZpb5b/1qNp+zbNylr0qd6pXYuOEY/H6fQ7WgR8zXwej8dlx1bshP1r29Zsi04dWnTv2sdaaNGtNQb+ju/5f3dDatK1Wes2PVu4mncgdurcomPHHl2bdsM0b9K9ScWTCAQCquIdMnQIRBjWkdaEMUQ03KFX3Iy/jkWgvg5EIYbCnYry7ScKwfmfT3b/4pVK2ScXmHsfIBhDkcrXlu3i+uXweNn/PNc/sDMCcVOPQJyXuubu/vzg5//vGvH/lBvlY5Prbi/651L/aSnjgMapdz/1SfE/K1MIxKDo/1r2/q/l//nb/xTUr1ssggRoCBaCB0QIOUIHrAgvIgqyiAKi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_4 {
            get {
                return ResourceManager.GetString("irb1666ID_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNxlmNNY3CjwJm2kaZrU3d3dBxjcHRa3AQZb3AZ3d3fZhV3c2cXddXFffHB3Blnuv9z3w/vcj/f8nmn6zEyTJjk953+sHITD4fyAlN1mE43CQ73a7dp37lKmS6dOXTr7TPXyu/do36Vz8UQgEginQol4IBwORcM+U5leHXv26p5fvHN+r57d8zr6TDV7tezYvlWV/L51u/ya37l4PB6JpML56WSrZDwej4aw7EGkP/cdqJDfpVN+z+59A9Xye7Tjwe+J3v/3MFRe91bt2vfOj7buxO/SNb9z517dW/bgtc7rmZf9J5Ik0ew7FDk5nGKwLd6OnMDnwhM2+3CvH5eDfhmMci734/48m68/UI7sf86s8OKV6hWeXBDvfcARDUcsr/3btU2+wd8X/c//psqV53CCGg7nvD66aPfnBz/+f7ec/ycpz5Qq269UswNXhPPLYqbOZfEHi0oL364sy+EMyf1fP3v/18//87v/SejPRx6HBEKOmKMCeo6Z4wIBTgwu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_5 {
            get {
                return ResourceManager.GetString("irb1666ID_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nNl1VBVf+Cj86RBbAUFKQVBpkC4DQaRUVJAOAWnpDgNBEVBUkFZBLEJEVKRUUkJEpKSRlpBueLff371r3ff+eeezzpmzDufsOTN772c/zwDBEAStg+3f/t+2EQFP589csnF0Oubk4ODkKMB13tLF1cbJUUFSSExIVFpEUkJIVFREXFSA65i7vZu7i6WCo6W7m4uZvQDXKXdzexsLdUvvs052lo4KEhJiYtKiljJSFlISEhLiIvi/g+z4r20hVUsnB0s3F28hTUvXSxh4n/T4n8NsMHOxuGTjYSl+0YF2umzp6OjuYu6KXTRzM/v3IYqikH+/cCsfBMmDvcIl6jaNghdb/j01OEEQshSIQBVO/3M2y+sItPN/nVnfz2Yt1eGGbcX90NZr8N6/gnm7DVfA3yP/12elw2kIigPN/GAXTypc6F//f91D/9e2Hmin7A6d+LJeF69s+emy8rlq1aPSp54rQ1CQ0v/xKP4/Hv+/9/5310DIf884tAHYCjFBbAA7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb1666ID_link_6 {
            get {
                return ResourceManager.GetString("irb1666ID_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1llBVntG3ruBsS3D24u2uA4O4Ed3d3d3e3QHAIEFyCu7skuAf3O/eu88a47/18PcfKWnt/VlXn0A0EGsNiGMYPPsTlw2/lPzWrtGzVvkPxDu3adWifIWmNZp27tOrQvmCuTFlzZsqaN2uuHJmyZc2SNWuGpMW7te3arXOzgu2bdevauXHbDEkrdfutbasm5Zr1qtahTbP2BXPmzJYtT9ZmeXM3yZ0zZ87sWRxySkzdPFPpZh3aNevauVemX5t1aWmn7+punuNt3LlJy1bdm2Vv2s7ToWOz9u27df6ti71p466NZZLb7bbKJYbTGEYBfFiHAmM9NkJI/rNhs9Wwfh5gNZZtturtfPlhNWJFb+3fC5crlH58PrLnvhEeYkn+KuP2BPW+Mt4uOjdPjGSGUSeRYZxLlH3+ro/3f/z/uvH/fMzqe+RAjcUDD9yrvWlFp2SjipOLW4zqxQ1jYOH/pT3/S/9X7/+8NoZcp91wGjawGw6SZBd9K+4kCW6trbhF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_base_link {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_base_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1jlF1p1K33PqeOGXeMTrpju2Pbtm3btm11bNu2nY5t+3vW2nXH+O79eesZM3O+6+VGuiqdpGKYhmH85kNcPvw2fqhaoVnzNm0Ltm3dum2b1ImqNO7QsXnbNrmzps2QJW2GHBmyZk6bMUP6DBlSJyrYuVWnzh0a527TuHOnDvVbpU5UrnODVs0blmzcvVLblo3b5M6SJWPG7Bka58jWMFuWLFkypXfILtF08bRFG7dt3bhTh+5pSzfu2CyCuquLtY+3foeGzZp3aZypUWtP23aN27Tp3KFBx4hG9TvVl0Fut9smRwz/bRi58MFtc43y2Akh+SH7xQjD9q2vzUh9MUIv5/tvmxE98tIeXLxSpujTC1H2PDTCA80kb9Jsi1vrB/0fLlhjsw/MYhgxMxjG+fiZ5uz68vD3/68b/8+HaQw6cHNj7QO/+8YuaO5dj+YWNPulL2QY/fL+L+35X/q/av/n2Rg2XSx+5KI2kmAz4ik2ww5xUQTEQQ6Ijf6A2FQc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_1 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1ltBRXtK272l1wd3d3d3eCu7sT3CFAgru7u7u7e5Dgwd2Dc7+16rwx7ns/3/nGZM619q69d1V3H0gCxGJYLJZffInLl9/KD7WqtW7TsVPxTh06dOqYIclvLbp2a9OpY8FcmbLmzJQ1b9ZcOTJly5ola9YMSYr3aN+9R9cWBTu26NG9a5P2GZJU6dG0fZtm5Vv0rtGpXYuOBXPmzJYtT9YWeXM3y50zZ87sWRyyS3RdPFPpFp06tOjetXemii26tbbTd/U09/E26dqsdZueLbI37+Dp1LlFx449ujbtZm/epHsTmeR2u61yxHBqi6UAPrxTgb88NkJIfpg/2Gaxfh1otUwebNPb+fbLaokRdWsPLl+tVPrppci+h5bwUCPZm4w74tf/znj9qLl5sqSyWM4ntVguJsw+d8/nh7/+f93y/3z9+uUr1qnu7EO/Bm4obgyaU/zXrwYHjc6XSlgsgwr/L+37X/q/ev/ntbHIjdssDtyK20mSnRYDrGSn4tLa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_2 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ11uFVV1O73Wrt7H7pbuhspKQHpUEBCOiRFQAFJFQQRCWkkRbq7U0QQJKW7u1Pi+40x932e794/7/k973nfMdZcc80Vex+Qc44Oy+FwvONDXD5CNp8a1G3foUvXCl07d+7aJXeGT9p0/7JD1y6li+YtUCRvgRIFihbOW7BA/gIFcmeo0LNTj57d25Tu0qZnj+4tOuXOULtny04dWlVr07t+145tupQuUqRgweIF2pQo1qpYkSJFCuV3y1ES6+R5K7fp2rlNj+6989Zo82V7F31vL3OcQIvurdp36NWmUOvO/q7d2nTp0rN7yy9drVv0aCGDfD6fLUuMZXM4SuHfdy01wu8kROWT+5nbYb8aYDtePnXr6fz3znYkiZ/alaPHa1a+eSRh61VH7Fsr04M861M3ec327fGxxWsw4ZjiDsfhtIWmbX5x9d3/rzv+nw/LsW1b4UJJd965sapiu2vOio3b965gffCgosMxsOz/0tb/pf+r93/ujUNO/CNHNSa0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_3 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1luFVltIV3dx06pUG6U7pTuhRJ6U4p6e7u7k5FQFq6u0ukuzvuO+e3f9zn/rznfQZjzLm+WmvvA4KHg8VqsVi+8SEuHwEbP9Su1qJlu/Yl2rdt275dpuS1mnbq3LJ9u0J5smTPnSV7/ux5cmXJkT1b9uyZkpfo2qZL105NC7Vr2rVLp0ZtMiWv0rVxm5ZNKjTtUaN966btCuXOnSNHvuxN8+dtkjd37tw5szlll9i6eJYyTdu3bdqlU48slZp2buGg7+5m9vE16tSkRctuTXP+2tbbvkPTdu26dmrc2fFroy6NZJDH47HJESPpLJaC+OD2BUd57YSw/GBv4rLYPva1Wd41duntfPpms8SJ3trtsxd+LPPgTMzOO5bIQGvK55m3JK73mes7o2Pz3c9lsezLY7GcTppzzvb3d779f93yfz6+FflSwmq5vmdvi5Mlf2q+u6TV8rB4wQv3S1os/Yr8L+38X/o/veiHTeWwWMFmsZMEp9ZW3Hw4LS7wIzf4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_4 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJ1jtGXJ1m23vfdJnbRt27Zt27Zt26xK27ZtVdq28fU547zWvvd+vuxt1BgxV2hFrFO3btFitVgsf/klLr8CNn5To3LLVu07FOnQrl2H9mkTVm/WuUurDu3zZU+fKVv6TLkyZc+aPnOmjJkypU1YpFvbrt06N8vXvlm3rp0btU2bsGK3xm1bNSnTrFfVDm2atc+XLVvmzDkzNcuVo0mObNmyZcnolFWi6uTpSzTr0K5Z18690pdr1qWlg7q7u1nH16hzk5atujfL0rSdt0PHZu3bd+vcuIujaaOujaSTx+OxyRYjpbBY8uLDOuQd67UTwuQ3i05YLbYfA2yWaSfMC/38a7NEi3i1R5evlS/x/FLkfY8tkYZYE79LtyNO3V88rxfRN2feSBZLxygWy8V4Webv+fb47/+vW/6fX3//XVnUahl+8O+/F4taZ+4tarEMLGyd+US8wP/Svv+l/6v2f+7GIi/utLgtDnBaXCTJHosdHGSPZi/9bLiHJPi0bcOt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_5 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nJx1WFXbt7D33uzE7u4ubAUVu7tbsLAVuxW7u7sVu1sEG1sUO1AURMRCRUERvneMfe7z3O/78/M9r2PMWHPNtdaYnHPPPT8NRoPBkMwvifIrpYnfOrTu13+Ibx3fwYN9h5TM295n+Ij+vkM8K7mVrehW1qNspQpu5cqWKVu2ZN46owaNHDXcx3OIz6iRw3sMKpm35aieg/r3auIzrq3vQJ8hnhUrlivnXtbHo3KvyhUrVixfxiJ3yaCLuzXw8R3sM3L4OLdmPiP6mem3jXbex7XH8F79+o/2Kd97sMN3qM+QIaOG9xxh7t1jZA+ZZLfbTbLFtEUMhmrEmb7VFjhcSNLIb39+GQymP34mw5dfzsf5m2wyZPzv0SIePmneIDo0XVCkIe10Y/5vpc7k6JrI+Mn/5roXczUY9qcwGB7kKr/pfHxk8v9vNPw/v5KDAuoaDeMv/Xz+sK5xylXJa6f0iahrMEyp8b8M+l/+X33/820M8uBVeeyxMI7MGauQVSXW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string irb4600_40_2_55_link_6 {
            get {
                return ResourceManager.GetString("irb4600_40_2_55_link_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IRB4600_Icon {
            get {
                object obj = ResourceManager.GetObject("IRB4600_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Movement_Icon {
            get {
                object obj = ResourceManager.GetObject("Movement_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Movement_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Movement_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Naming_Icon {
            get {
                object obj = ResourceManager.GetObject("Naming_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PathGen_Icon {
            get {
                object obj = ResourceManager.GetObject("PathGen_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PathGen_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("PathGen_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Plane_Visualizer_Icon {
            get {
                object obj = ResourceManager.GetObject("Plane_Visualizer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RAPID_Icon {
            get {
                object obj = ResourceManager.GetObject("RAPID_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReadDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("ReadDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remote_OFF_Icon {
            get {
                object obj = ResourceManager.GetObject("Remote_OFF_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remote_ON_Icon {
            get {
                object obj = ResourceManager.GetObject("Remote_ON_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RobotInfo_Icon {
            get {
                object obj = ResourceManager.GetObject("RobotInfo_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RobotInfo_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("RobotInfo_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SetDigitalInput_Icon {
            get {
                object obj = ResourceManager.GetObject("SetDigitalInput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SetDigitalOutput_Icon {
            get {
                object obj = ResourceManager.GetObject("SetDigitalOutput_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpeedData_Icon {
            get {
                object obj = ResourceManager.GetObject("SpeedData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SpeedData_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("SpeedData_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Target_Visualizer_Icon {
            get {
                object obj = ResourceManager.GetObject("Target_Visualizer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timer_Icon {
            get {
                object obj = ResourceManager.GetObject("Timer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timer_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Timer_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tool_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("Tool_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToolData_Icon {
            get {
                object obj = ResourceManager.GetObject("ToolData_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ToolPlane_Icon {
            get {
                object obj = ResourceManager.GetObject("ToolPlane_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WaitDI_Icon {
            get {
                object obj = ResourceManager.GetObject("WaitDI_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WaitDI_Parameter_Icon {
            get {
                object obj = ResourceManager.GetObject("WaitDI_Parameter_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
