name: CI - Build, Test & Artifacts (.NET Framework 4.8)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild /t:Restore,Build /p:Configuration=Release

      - name: Run tests from RobotComponents.Tests
        shell: pwsh
        run: |
          # Find vstest.console.exe installed with Visual Studio
          $vstest = Get-ChildItem "C:\Program Files" -Recurse -Filter "vstest.console.exe" -ErrorAction SilentlyContinue | Select-Object -First 1
          if (-not $vstest) {
            Write-Error "vstest.console.exe not found on this runner."
            exit 1
          }
          Write-Host "Using vstest.console.exe at: $($vstest.FullName)"

          # Try to locate the test DLL automatically
          $testDll = Get-ChildItem -Recurse "RobotComponents.Tests\bin" -Filter "RobotComponents.Tests.dll" -ErrorAction SilentlyContinue | 
            Where-Object { $_.FullName -match "Release|Debug" -and $_.FullName -match "net48" } | 
            Select-Object -First 1

          if (-not $testDll) {
            Write-Error "Test DLL not found under RobotComponents.Tests\bin"
            exit 1
          }

          Write-Host "Found test assembly at: $($testDll.FullName)"
          & "$($vstest.FullName)" "$($testDll.FullName)" /Logger:"trx;LogFileName=TestResults.trx"

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults.trx'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/Release/**
            !**/obj/**
