name: CI - Build & Test (.NET Framework 4.8)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild /t:Restore,Build /p:Configuration=Release

      - name: Run tests (produce TRX)
        run: |
          vstest.console.exe **\*test*.dll /Logger:"trx;LogFileName=TestResults.trx"
        continue-on-error: true  # allows job to continue even if tests fail

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults.trx'
